### PR TITLE
Added Fibonacci Testing

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [x] I names the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[3]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/CODE_ARTICLE_TEMPLATE.md
[4]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/LANGUAGE_ARTICLE_TEMPLATE.md
[5]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md

### CODE REVIEW

**Comment by auroq** [comment]
Still a few failing languages here that I'm not super familiar with. I'll take a look at them tomorrow or Monday if no one wants to jump in and get them first.

**Comment by jrg94** [comment]
Pulled in master (testing out the new build feature).

**Comment by jrg94** [comment]
Yay, it works! 🐺

**Comment by jrg94** [comment]
Obviously, you know which tests failed, but I'm going to dump them here in case I get to them first:

```
=================================== FAILURES ===================================
________________ test_fibonacci_invalid[fibonacci.jl-no input] _________________
description = 'no input', in_params = None
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: BoundsError: attempt to access 0-element Array{String,1} at index [1]
E         - Stacktrace:
E         -  [1] getindex(::Array{String,1}, ::Int64) at ./array.jl:729
E         -  [2] top-level scope at none:0
E         -  [3] include at ./boot.jl:326 [inlined]
E         -  [4] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [5] include(::Module, ::String) at ./sysimg.jl:29
E         -  [6] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [7] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:77: AssertionError
_______________ test_fibonacci_invalid[fibonacci.jl-empty input] _______________
description = 'empty input', in_params = '""'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: ArgumentError: input string is empty or only contains whitespace
E         - Stacktrace:
E         -  [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:95
E         -  [2] #parse#348(::Nothing, ::Function, ::Type{Int64}, ::String) at ./parse.jl:238
E         -  [3] parse(::Type{Int64}, ::String) at ./parse.jl:238
E         -  [4] top-level scope at none:0
E         -  [5] include at ./boot.jl:326 [inlined]
E         -  [6] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [7] include(::Module, ::String) at ./sysimg.jl:29
E         -  [8] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [9] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:77: AssertionError
_______ test_fibonacci_invalid[fibonacci.jl-invalid input: not a number] _______
description = 'invalid input: not a number', in_params = '"a"'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: ArgumentError: invalid base 10 digit 'a' in "a"
E         - Stacktrace:
E         -  [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:131
E         -  [2] #parse#348(::Nothing, ::Function, ::Type{Int64}, ::String) at ./parse.jl:238
E         -  [3] parse(::Type{Int64}, ::String) at ./parse.jl:238
E         -  [4] top-level scope at none:0
E         -  [5] include at ./boot.jl:326 [inlined]
E         -  [6] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [7] include(::Module, ::String) at ./sysimg.jl:29
E         -  [8] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [9] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:77: AssertionError
________________ test_fibonacci_invalid[fibonacci.cpp-no input] ________________
description = 'no input', in_params = None
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c-plus-plus
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:77: AssertionError
______________ test_fibonacci_invalid[fibonacci.cpp-empty input] _______________
description = 'empty input', in_params = '""'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c-plus-plus
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:77: AssertionError
______ test_fibonacci_invalid[fibonacci.cpp-invalid input: not a number] _______
description = 'invalid input: not a number', in_params = '"a"'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c-plus-plus
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:77: AssertionError
_______________ test_fibonacci_invalid[fibonacci.c-empty input] ________________
description = 'empty input', in_params = '""'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:77: AssertionError
_______ test_fibonacci_invalid[fibonacci.c-invalid input: not a number] ________
description = 'invalid input: not a number', in_params = '"a"'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:77: AssertionError
==================== 8 failed, 514 passed in 235.31 seconds ====================
The command "python -um samplerunner test" exited with 1.
```

**Comment by jrg94** [comment]
Looks like Travis also has a nice line linking feature: https://travis-ci.com/TheRenegadeCoder/sample-programs/jobs/190973308#L1027-L1183

**Comment by jrg94** [comment]
Looks like there's only 3 left (Julia and C). I'll take a crack at Julia:

```
=================================== FAILURES ===================================
________________ test_fibonacci_invalid[fibonacci.jl-no input] _________________
description = 'no input', in_params = None
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: BoundsError: attempt to access 0-element Array{String,1} at index [1]
E         - Stacktrace:
E         -  [1] getindex(::Array{String,1}, ::Int64) at ./array.jl:729
E         -  [2] top-level scope at none:0
E         -  [3] include at ./boot.jl:326 [inlined]
E         -  [4] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [5] include(::Module, ::String) at ./sysimg.jl:29
E         -  [6] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [7] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:78: AssertionError
_______________ test_fibonacci_invalid[fibonacci.jl-empty input] _______________
description = 'empty input', in_params = '""'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: ArgumentError: input string is empty or only contains whitespace
E         - Stacktrace:
E         -  [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:95
E         -  [2] #parse#348(::Nothing, ::Function, ::Type{Int64}, ::String) at ./parse.jl:238
E         -  [3] parse(::Type{Int64}, ::String) at ./parse.jl:238
E         -  [4] top-level scope at none:0
E         -  [5] include at ./boot.jl:326 [inlined]
E         -  [6] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [7] include(::Module, ::String) at ./sysimg.jl:29
E         -  [8] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [9] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:78: AssertionError
_______ test_fibonacci_invalid[fibonacci.jl-invalid input: not a number] _______
description = 'invalid input: not a number', in_params = '"a"'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/julia
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       assert 'ERROR: LoadE...bonacci.jl:11' == 'Usage: please...ers to output'
E         + Usage: please input the count of fibonacci numbers to output
E         - ERROR: LoadError: ArgumentError: invalid base 10 digit 'a' in "a"
E         - Stacktrace:
E         -  [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:131
E         -  [2] #parse#348(::Nothing, ::Function, ::Type{Int64}, ::String) at ./parse.jl:238
E         -  [3] parse(::Type{Int64}, ::String) at ./parse.jl:238
E         -  [4] top-level scope at none:0
E         -  [5] include at ./boot.jl:326 [inlined]
E         -  [6] include_relative(::Module, ::String) at ./loading.jl:1038
E         -  [7] include(::Module, ::String) at ./sysimg.jl:29
E         -  [8] exec_options(::Base.JLOptions) at ./client.jl:267
E         -  [9] _start() at ./client.jl:436
E         - in expression starting at /src/fibonacci.jl:11
test/projects/test_fibonacci.py:78: AssertionError
_______________ test_fibonacci_invalid[fibonacci.c-empty input] ________________
description = 'empty input', in_params = '""'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:78: AssertionError
_______ test_fibonacci_invalid[fibonacci.c-invalid input: not a number] ________
description = 'invalid input: not a number', in_params = '"a"'
expected = 'Usage: please input the count of fibonacci numbers to output'
fibonacci = Source(name: fibonacci, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/c/c
    @pytest.mark.parametrize(invalid_permutations[0], invalid_permutations[1],
                             ids=[p[0] for p in invalid_permutations[1]])
    def test_fibonacci_invalid(description, in_params, expected, fibonacci):
        actual = fibonacci.run(params=in_params)
>       assert actual.strip() == expected
E       AssertionError: assert '' == 'Usage: please input the cou...fibonacci numbers to output'
E         + Usage: please input the count of fibonacci numbers to output
test/projects/test_fibonacci.py:78: AssertionError
==================== 5 failed, 517 passed in 133.15 seconds ====================
```

**Comment by jrg94** [comment]
Julia is patched! C is still broken.

**Comment by auroq** [comment]
Finally got time to work on this. I think we have everything covered. Assuming the build passes, we should be good to go.

**Pull request merged**
