### PR TITLE
Add Even Odd in Pascal #2217

### LINKED ISSUE #2217: Add Even Odd in Pascal
To request a new code snippet, please fill out the following:

Project name: Even Odd Sample Program in Pascal
Project link: https://sample-programs.therenegadecoder.com/projects/my-project-name
Language: Pascal

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/

### PR DESCRIPTION
**Pull request by smjalageri**
Created Even & Odd Check in Pascal

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [X] I fixed #2217 
- [X] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

  
## I Am Adding a New Code Snippet in a New Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
- [ ] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])
  

## I Am Adding New Tests for a Project

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} tests` format
- [ ] I verified the project exists on the [Sample Programs Project List][sample-programs-project-list]
- [ ] I added tests for every test case in the Testing table of the project description for the given project. (See [contributing documentation][contributing-tests-in-detail])

  
## I Am Modifying an Existing Code Snippet or Existing Tests

- [ ] I fixed #your-issue-number-here
- [ ] I have read about modifying existing code snippets or tests in the [contributing documentation][contributing-modifications]
- [ ] I have explained why this modification is _necessary_ either in the issue linked above or in the notes below
- [ ] I named the pull request using `Modify {PROJECT} {tests} in {LANGUAGE}` format

## Other Notes

Add notes here...

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by auroq — CHANGES_REQUESTED** [review]
Could you add this program to readme?

https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes

**Comment by auroq** [comment]
We just got the testing hooked up for Pascal to review your PRs.
Looks like some things are not quite right. Take a look the Travis CI build to see what's failing. In many cases it's some minor formatting changes.

Refer to the Tests in Detail section of our contributing doc if you need more information about how we do testing:
https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail

**Comment by smjalageri** [comment]
I need help here, ..

I'm using 

Free Pascal Compiler version 3.2.0 [2020/06/14] for x86_64 on Ubuntu 16.04

On Local Machine and also on https://www.jdoodle.com/execute-pascal-online/ (Uses Free Pascal Compiler version 3.0.4 [2018/04/10] for x86_64)

I'm able to get the right output..

However, 
The Build Job is failing for 2, 5, -14, -27

Extract from Build #4962 ....
test/projects/test_even_odd.py::test_even_odd_valid[even_odd.pas-sample input: even] FAILED [ 12%]
test/projects/test_even_odd.py::test_even_odd_valid[even_odd.pas-sample input: odd] FAILED [ 12%]
test/projects/test_even_odd.py::test_even_odd_valid[even_odd.pas-sample input: negative even] FAILED [ 12%]
test/projects/test_even_odd.py::test_even_odd_valid[even_odd.pas-sample input: negative odd] FAILED [ 12%]


test/projects/test_even_odd.py::test_even_odd_invalid[even_odd.pas-no input] PASSED [ 12%]
test/projects/test_even_odd.py::test_even_odd_invalid[even_odd.pas-empty input] PASSED [ 12%]
test/projects/test_even_odd.py::test_even_odd_invalid[even_odd.pas-invalid input: not a number] PASSED [ 12%]


Kindly provide me the Pascal Configuration being used on the Repo.

**Review by jrg94 — APPROVED** [review]
Looks like things shaped up! I think there's some weird spacing issues with this solution as well, but I think I'm going to pass through all of them with a linter shortly.

**Pull request merged**
