### PR TITLE
Hello World in Orc

### PR DESCRIPTION
**Pull request by BassemMohamed**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [x] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [ ] I fixed #your-issue-number-here

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by BassemMohamed** [comment]
No! sorry about that, What should i do now ?!

**Comment by chrboe** [comment]
Do you know how to remove the extra merge commit using an interactive rebase?
If not, I can just merge the PR manually.

**Comment by BassemMohamed** [comment]
I am not sure i know what you mean, i updated my fork using a pull request if this is not enough, you can tell me what to do OR merge manually.

**Comment by chrboe** [comment]
I just squashed the commits into one, so that eliminates the problem.

If you want, we can look into what went wrong there on Gitter

**Pull request merged**
