### PR TITLE
Added Jump Search in Python

### PR DESCRIPTION
**Pull request by soumalyatheking22012001**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- 

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format

- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks good, but we need to get it documented before we include it.

**Comment by soumalyatheking22012001** [comment]
What type of documentation you need please let me know. So that I can help

**Comment by jrg94** [comment]
For sure! We document everything here: https://github.com/TheRenegadeCoder/sample-programs-website

**Comment by soumalyatheking22012001** [comment]
Can you please add the hacktoberfest label in this PR

**Comment by soumalyatheking22012001** [comment]
I can give the entire documentation of my program but I can't actually understand the template provided and where to put my documentation

**Comment by auroq** [comment]
> I can give the entire documentation of my program but I can't actually understand the template provided and where to put my documentation

Sorry for confusion. We recently split this repo into two, and we're still working on getting documentation transfered over.

Basically, we only accept code implementations for projects that have explanations here: https://sample-programs.therenegadecoder.com/projects/

So, before we can merge this, you will need to make a pull request to this repo. https://github.com/TheRenegadeCoder/sample-programs-website

Add a new folder here. https://github.com/TheRenegadeCoder/sample-programs-website/tree/master/projects

Create an index.html that describes the project.
Jump search would be a great addition.
Take a look at either of these for examples:

https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/projects/binary-search/index.md

https://github.com/TheRenegadeCoder/sample-programs-website/tree/master/projects/linear-search

Once that is done, since this is a new project,  you will also need to add tests in addition to the code snippets. Take a look at the contributing document on how to do that. I can also help with that part if you need.

**Comment by auroq** [comment]
> Can you please add the hacktoberfest label in this PR

Our whole repo is labeled with hacktoberfest, so you should get credit for any PRs here with or without the label on the PR. That said, I can still add it if you'd like.

**Comment by soumalyatheking22012001** [comment]
https://github.com/TheRenegadeCoder/sample-programs-website/pull/354 
I added the documentation in the given repo. As suggested by @auroq I have put the index.html file there

**Pull request closed without merging**
