### PR TITLE
Added F Sharp Testing

### LINKED ISSUE #1124: Add F Sharp Testing
If possible, please provide the link(s) to a Docker Hub image which would support the language you are requesting:
  - https://hub.docker.com/path/to/image
  - https://hub.docker.com/path/to/image-slim

If possible, please provide a style guide which details file naming conventions for the language you would like supported:
  - https://example.com/path/to/style-guide

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1124 

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [x] I names the pull request using `Added/Updated <Language>/<Project> Testing` format
- [x] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[3]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/CODE_ARTICLE_TEMPLATE.md
[4]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/LANGUAGE_ARTICLE_TEMPLATE.md
[5]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md

### CODE REVIEW

**Comment by auroq** [comment]
Hmm... It worked on my machine. haha. I'll take a look.

**Comment by jrg94** [comment]
Long time no see!

**Comment by auroq** [comment]
I am not able to replicate this error on any machines I have tried. @jrg94, would you be able to try running this on your local machine?

**Comment by jrg94** [comment]
Looks like it's still failing. I was having a similar issue with Groovy, and I'm not sure how to fix it.

That said, I haven't tried setting up docker on my machine in awhile (had some trouble with that in the past). I can try to give it a go tonight tho!

**Comment by jrg94** [comment]
Doing some research on this error. Not sure what you tried, but here are some related links:

- https://staxmanade.com/2016/05/strange-error-on-docker-compose-up/

**Comment by jrg94** [comment]
Actually, I had a different issue with Groovy:

```python
def test_hello_world(hello_world):
        actual = hello_world.run()
>       assert actual.strip() == 'Hello, World!'
E       AssertionError: assert 'Caught: java.../hello-world)' == 'Hello, World!'
E         + Hello, World!
E         - Caught: java.io.FileNotFoundException: /tmp/hsperfdata_groovy/hello-world (/tmp/hsperfdata_groovy/hello-world)
E         - java.io.FileNotFoundException: /tmp/hsperfdata_groovy/hello-world (/tmp/hsperfdata_groovy/hello-world)
```

**Comment by jrg94** [comment]
Gonna copy the error here for reference:

```
=================================== FAILURES ===================================
_______________________ test_hello_world[HelloWorld.fs] ________________________
hello_world = Source(name: HelloWorld, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/f/f-sharp
    def test_hello_world(hello_world):
        actual = hello_world.run()
>       assert actual.strip() == 'Hello, World!'
E       assert 'OCI runtime ...ror": unknown' == 'Hello, World!'
E         - OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec format error": unknown
E         + Hello, World!
test/projects/test_hello_world.py:18: AssertionError
================== 1 failed, 578 passed in 234.59s (0:03:54) ===================
The command "python -um samplerunner test" exited with 1.
```

**Comment by jrg94** [comment]
FYI: GitHub Desktop requires Windows Pro or Enterprise which I apparently don't have. I may virtualbox it with Ubuntu...

**Comment by auroq** [comment]
Hmm... I just got it to run on my surface and it is failing on windows. Maybe that will give me some insight.

**Comment by auroq** [comment]
@jrg94 I got this to work by executing the compiled file using mono.

When using fsharpc to build in a linux docker container on a _linux_ host, a binary is created that can just be executed. However, building in a linux docker container on a _windows_ host, the binary cannot be executed. :man_shrugging: 

Running the binary with mono solves the problem.

While debugging this, I also came across another unrelated issue and created an issue for it: #1126

**Comment by jrg94** [comment]
Interesting! Glad you were able to isolate the issue. I'm curious how the whole Windows issue ties in with the Travis CI issue (since it's Ubuntu). At any rate, it looks like everything works now, so I'm not too worried about it. 💯

**Pull request merged**
