### PR TITLE
Merging in Baklava from Another Repo

### LINKED ISSUE #417: Add Baklava Solution to Repo
We got the go ahead: https://github.com/toturkmen/baklava/issues/10#event-1844507338

### PR DESCRIPTION
**Pull request by jrg94**
Alright, this was a bit complicated, but I think I got everything working. 

At any rate, what I've done is merge in the entire Baklava repo as detailed in #417. I did this to try to give credit to the folks who worked on those solutions at least through `git blame`. For whatever reason, all the files have been attributed to me, but you can clearly see the git history here. In addition, `git blame` let's you dig into who is responsible for each snippet. 

Feel free to tear into this. I'm looking for an honest review of what I've done to get these scripts into our repo. If this seems alright, perhaps we can do something similar for the other outstanding issues related to repo merging.

If we like this, we can close #417.

### CODE REVIEW

**Comment by jrg94** [comment]
If it makes sense, we can just squash this history. I'm no git expert, but I imagine all the blame history should at least be there.

**Comment by chrboe** [comment]
If you squash, everything is rewritten into a single commit, so consequently the commit history (which `git blame` uses) is lost permanently.

Just from looking at it it seems like you handled this very well (all the author information is still there etc). If you really wanted to make it look nicer, you could squash just the commits you added on top of theirs.

**Comment by chrboe** [comment]
What about the language readme files? They should still include a reference to the original repo, right?

**Comment by chrboe** [comment]
Oof, I just looked at how this would look when it's merged, and it's a little messy. The issue is that the date of the commit got preserved, so all the commits show up as having been commited in 2017. A solution to this would be changing the commit date and preserving the author date, which would make much more sense for this application.
I'm currently locally trying to make this work, I'll get back to this PR once it works.

**Comment by jrg94** [comment]
Awesome! Baklava will need to be added to the appropriate READMEs once everything is cleaned up. Also, We should verify the Contributing Doc description makes sense.

**Comment by chrboe** [comment]
> If it makes sense, we can just squash this history.  I'm no git expert, but I imagine all the blame history should at least be there.

Ah, I think I just realized what you meant by that. Yes, the author information will get preserved, but not the individual commits (i.e. it will show "Authored by toturkmen, commited by jrg94").

Now that I've struggled with this quite a bit, I think that just squashing it and living with it being in the past is probably the best option we have. Although it seems that interactive rebasing isn't really trivial either when subtrees get involved, since they're not **technically** part of the history (you essentially split the repo so that it has two "first commits", which only join together in [commit 492291 (Merge branch 'master' into baklava-merge)](https://github.com/TheRenegadeCoder/sample-programs/pull/420/commits/492291eeaaabc0b664502496c487fc059205a776).

You're **really** stretching my git-fu here, but I'm reasonably sure that if you manage to squash the subtree commits (and only the subtree commits) that should flatten the history and act just like a regular pull request. But I'm by no means sure on that...

**Comment by jrg94** [comment]
@chrboe is there any chance you could try to perform that squash? Haha I’m not sure I’d be able to pull it off. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Worst-case scenario, whatever you do happens in this branch and not master. I can deal with that haha

**Comment by jrg94** [comment]
We can even test this squash on another branch and see how it goes.

**Comment by jrg94** [comment]
Alright, I tried squashing everything here into a new branch: https://github.com/TheRenegadeCoder/sample-programs/tree/baklava-squash

It did not go as expected. Git Blame history is gone.

**Comment by jrg94** [comment]
Alright, I'm comfortable with this solution. I'll give it 24 hours or so for review before I just pull the trigger on squashing all the history. Feel free to try to clean things up before then.

**Pull request merged**
