### PR TITLE
Fizz Buzz in Pascal

### LINKED ISSUE #517: Add Fizz Buzz in Pascal
If this is your first time contributing, create the Fizz Buzz file in the appropriate directory and add the name of the program to the Sample Programs section of the language README. Then, create a new issue for its article like #30. Link this issue in the README and create a pull request when you're done.

### PR DESCRIPTION
**Pull request by EdoRguez**
- [x] I fixed #517 

## Notes

I added Fizz Buzz program in Pascal.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by EdoRguez** [comment]
@jrg94 I would like to update it, but I need the properly link, like this example.

- [Hello World in Pascal] (https://therenegadecoder.com/code/hello-world-in-pascal/)

- [Fizz Buzz in Pascal] (I need link for this one)

**Comment by jrg94** [comment]
Unfortunately, the article hasn't been written yet. You're welcome to take a stab at it if you'd like.

In the meantime, we usually just link an issue there. You'll need to make a new issue like #30.

**Comment by jrg94** [comment]
Hey @EdoRguez! Just checking in.

**Comment by jrg94** [comment]
Here's the link: https://github.com/TheRenegadeCoder/sample-programs/issues/548

**Comment by jrg94** [comment]
I took care of it!

**Pull request merged**
