### PR TITLE
Added Various Programs in Java

### PR DESCRIPTION
**Pull request by BhuvaneshHingal**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [x] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [x] I followed the testinfo template, if applicable

## Notes
***Added 3 Java Programs***
- Binary Search
- Bucket Sort
- Radix Sort
*Also Updated the README.md with the above contents*

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by vivmost — APPROVED** [review]
looks good.

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is really great! There are a couple things that will need to be changed. First, is there any way you could pull these three programs out into separate branches? Second, binary search is the only program of the three that we have support for at the moment. Right now, it looks like it's failing testing: https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/187463818. Otherwise, nice work!

**Comment by BhuvaneshHingal** [comment]
@jrg94 So should I just add the Binary Search Program into another branch and then send a PR or should I add all the 3 programs to a new branch ?

**Comment by BhuvaneshHingal** [comment]
> I was thinking one branch for each program. That way we could potentially get your binary search program merged in sooner.

@jrg94 Hey! Can you please check have I done it correctly? #1949 #1950 #1951

**Comment by jrg94** [comment]
Yeah, this looks good. I'm going to close this one for now.

**Pull request closed without merging**
