### PR TITLE
Added Fibonacci in MATLAB

### LINKED ISSUE #1468: Add Fibonacci in Matlab
See requirements: https://sample-programs.therenegadecoder.com/projects/fibonacci/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/m/matlab

### PR DESCRIPTION
**Pull request by gabiherman**
generates the fibonacci sequence (not recursively)

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #1468 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### CODE REVIEW

**Comment by gabiherman** [comment]
Will make it callable now, thanks for reviewing so quickly! Also I accidentally updated the README in a separate PR, sorry about that.

**Comment by jrg94** [comment]
Same comment as #1768

**Comment by gabiherman** [comment]
Sorry!!! Working on both PRs now, something came up at work. Appreciate the reminder.

**Comment by jrg94** [comment]
No sweat! Just wanted to make sure we got your work merged. 😄

**Comment by gabiherman** [comment]
this should be fixed :)

**Pull request merged**
