### PR TITLE
Added Fibonacci in Perl

### LINKED ISSUE #1514: Add Fibonacci in Perl
See requirements: https://sample-programs.therenegadecoder.com/projects/fibonacci/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/perl

### PR DESCRIPTION
**Pull request by SourabhBadhya**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1514 

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — APPROVED** [review]
Great addition!

**Comment by SourabhBadhya** [comment]
I think there was a problem while merging the four pull requests that I had done. Only #1944 pull request was reflected on the master repo. The changes made by pull requests #1920 , #1929 , #1932 were not reflected in the master repo. This is probably due to the fact that #1944 is a branch which has commits wherein I have removed the other files mentioned in the other 3 pull requests. I request you to only merge the last commit rather than all the commits or if any other solution exists let me know.

**Comment by jrg94** [comment]
I see what you're saying! I tried reverting this change, but it seems the only code that comes back is the AutoHotKey script.

**Comment by jrg94** [comment]
I committed the revert. You may need to reopen this one. I'm not sure what to do about the other two pull requests: #1920 and #1929.

**Comment by SourabhBadhya** [comment]
I will add the all the files to this branch itself. Then just merge the files. I think this should work.

**Comment by SourabhBadhya** [comment]
Should I open a new pull request or you could reopen this pull request?

**Comment by SourabhBadhya** [comment]
I have opened a new pull request (#1991 ) which contains all the files. I think it will look fine after merging.

**Pull request merged**
