### PR TITLE
Added Linear Search in Java

### PR DESCRIPTION
**Pull request by Ashish7129**
Added Linear Search in Java as sample programs

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by Ashish7129** [comment]
Hi @jrg94 

I have added the counting sort algorithms in java. Can you please review this?

**Comment by Ashish7129** [comment]
I have added Linear Search in java also

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is great, but we usually only accept one solution at a time. Linear search is good to go (minus some failing tests). Counting sort is not currently supported in this repo. Feel free to help us document it though. https://sample-programs.therenegadecoder.com/projects/

**Comment by Ashish7129** [comment]
Hi @jrg94 

I have updated the code as per the test cases. Can you please check?

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks like this passes testing, but we still need you to remove CountingSort.java from the pull request. You can submit it in a separate on if you'd like.

**Comment by Ashish7129** [comment]
Hi @jrg94 ,

I have removed the counting sort and also from the Readme.md

**Review by jrg94 — APPROVED** [review]
Awesome! We're good to go.

**Comment by jrg94** [comment]
Hey @Ashish7129! If you enjoyed contributing to this project and would like to make sure that it continues to be maintained, we can always use your support at The Renegade Coder. Here are some ways you can help out:

- Subscribe to the [monthly newsletter](https://newsletter.therenegadecoder.com/)
- Become a [patron](https://www.patreon.com/TheRenegadeCoder)
- Join us on [Discord](https://discord.gg/Jhmtj7Z)
- And, check out the rest of the [list](https://therenegadecoder.com/blog/ways-you-can-help-grow-the-renegade-coder/) which includes links to The Renegade Coder [YouTube channel](https://www.youtube.com/channel/UCpyoVwOqYRlSAEUPEn7P9hw) and [Twitter account](https://twitter.com/RenegadeCoder94)

Thanks for your help!

**Pull request merged**
