### PR TITLE
Added Longest Palindromic Substring in C++

### PR DESCRIPTION
**Pull request by hemabhravee**

### CODE REVIEW

**Comment by hemabhravee** [comment]
Congrats on taking the first step to contributing to the Sample Programs repository maintained by The Renegade Coder!
For simplicity, please make sure that your pull request includes one and only one contribution.

Complete the Applicable Sections Below
Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

 I could not find an issue for this PR

Code Snippets
 I named the pull request using Added/Updated <Sample Program> in <Language> format
 I created/updated the language README
 I added the sample program name to the README
 I added fun facts (i.e. debut developer, typing, etc.)
 I added reference link(s) to the README
 I added solution citations when necessary (see plagiarism)
Testing
 I named the pull request using Added/Updated <Language>/<Project> Testing format
 I followed the testinfo template, if applicable
Notes
Feel free to describe what you added or updated.

**Comment by hemabhravee** [comment]
How can I get this code tested?

**Comment by jrg94** [comment]
We don't have tests written yet: https://github.com/TheRenegadeCoder/sample-programs/tree/master/test/projects

Would you like to help us with that? The expectation would be that you implement testing as seen here: https://sample-programs.therenegadecoder.com/projects/longest-palindrome-substring/

**Comment by hemabhravee** [comment]
Where can I find the documentation for glotter? I'm facing trouble understanding the testing code

**Comment by auroq** [comment]
HI @hemabhravee 
Information about Glotter can be found on the Glotter wiki here: https://github.com/auroq/glotter/wiki
Some basics about how we integrate with Glotter can be found here on our contributing documentation here: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail

**Comment by jrg94** [comment]
I think testing has been added. Any chance you could pull from master again?

**Pull request closed without merging**
