### PR TITLE
Bubble Sort in Python

### LINKED ISSUE #811: Add Article for Bubble Sort in Python
See #810

### PR DESCRIPTION
**Pull request by hmajid2301**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #811

### CODE REVIEW

**Comment by jrg94** [comment]
I’ll take a look later when I get the chance!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
I haven't dug into this too deep yet, but I am very, very impressed. You added yourself to the authors.yml file, created your own image, wrote a complete article, and updated the gitignore to include support for other editors. I'm really happy with this contribution, and I hope you consider helping again in the future! 😄

**Comment by auroq** [comment]
I want to add that I am very impressed with this article, as well. It is very thorough. I think @jrg94, covered everything. You even caught the nuance with passing both `xs` and `xs[:]` to reduce.

**Comment by hmajid2301** [comment]
Image Source: https://nyoobserver.files.wordpress.com/2017/03/soap-bubble-colorful-ball-soapy-water.jpg?quality=80&w=635&h=384

**Comment by jrg94** [comment]
Actually, as far as I can tell, this image comes from Pixabay, so I think we're safe:

https://www.pexels.com/photo/colorful-ball-float-soap-bubble-35828/

**Comment by hmajid2301** [comment]
That's good I did select the free for non commercial use in Google search as well.

**Comment by jrg94** [comment]
Oh cool! I didn't know you could do that in Google. That's good to know.

I added a couple minor changes of my own to the article (front matter bug and opening sentence). If you're happy with everything, I'll merge!

**Pull request merged**
