### PR TITLE
Added Merge Sort in C

### LINKED ISSUE #1267: Add Merge Sort in C
See requirements: https://sample-programs.therenegadecoder.com/projects/merge-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c

### PR DESCRIPTION
**Pull request by panda311**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1267

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

### CODE REVIEW

**Comment by panda311** [comment]
I don't get why it is failing the checks . It runs perfectly on my system .

**Comment by jrg94** [comment]
We use Docker to test code, and Docker is currently down. You may have to wait a bit to rerun your code. See random discussions strewn about in #1630, #1633, #1631 (etc.).

**Comment by jrg94** [comment]
Now, you should be able to see exactly what the errors are here: https://travis-ci.com/TheRenegadeCoder/sample-programs/jobs/245927112

Looks like GCC is failing to build. Are you using an external library?

**Comment by panda311** [comment]
It was my fault , I forgot to add escape character in string. 
Do I have to again create a pull request or a change can be made without it.

**Comment by jrg94** [comment]
See:

```
E               RuntimeError: unable to build using cmd "gcc -o merge-sort merge-sort.c ":
E               merge-sort.c:4:9: fatal error: conio.h: No such file or directory
E                #include<conio.h>
E                        ^~~~~~~~~
E               compilation terminated.
```

**Comment by panda311** [comment]
I have made the required changes in program but a new file has been added to list , thus there is a conflict in README.md .

**Comment by jrg94** [comment]
I was able to fix the conflict on my end!

**Comment by panda311** [comment]
Finally , all checks are cleared . Pls merge ...

**Pull request merged**
