### PR TITLE
Update Fizz Buzz in Python to Address Performance Issues

### LINKED ISSUE #2118: Update Fizz Buzz in Python to Address Performance Issues
I want to redo the current Fizz Buzz in Python program as it's inefficient and can be improved.

[Project Link](https://sample-programs.therenegadecoder.com/projects/fizz-buzz/t)

### PR DESCRIPTION
**Pull request by xPolar**
## Complete the Applicable Sections Below

- [x] I fixed #2118 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Change `range(1, 101)` to `range(101)`, use inline if statements as well as use much less lines.

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks like this is failing testing. Take a peek at the output in Travis.

**Comment by xPolar** [comment]
How would I take a peek at the test output? Travis just shows me that it failed.

**Comment by jrg94** [comment]
It looks like it printed FizzBuzz for 0: https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/188088024

**Review by jrg94 — APPROVED** [review]
Awesome! Works great.

**Comment by jrg94** [comment]
Hey @xPolar! If you enjoyed contributing to this project and would like to make sure that it continues to be maintained, we can always use your support at The Renegade Coder. Here are some ways you can help out:

- Subscribe to the [monthly newsletter](https://newsletter.therenegadecoder.com/)
- Become a [patron](https://www.patreon.com/TheRenegadeCoder)
- Join us on [Discord](https://discord.gg/Jhmtj7Z)
- And, check out the rest of the [list](https://therenegadecoder.com/blog/ways-you-can-help-grow-the-renegade-coder/) which includes links to The Renegade Coder [YouTube channel](https://www.youtube.com/channel/UCpyoVwOqYRlSAEUPEn7P9hw) and [Twitter account](https://twitter.com/RenegadeCoder94)

Thanks for your help!

**Pull request merged**
