### PR TITLE
Added Longest Palindromic Substring in JavaScript

### LINKED ISSUE #2245: Add Longest Palindromic Substring in JavaScript
To request a new code snippet, please fill out the following:

Project name: Longest Palindromic Substring
Project link: https://sample-programs.therenegadecoder.com/projects/longest-palindrome-substring/
Language: JavaScript

### PR DESCRIPTION
**Pull request by izexi**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #2245
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [x] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by jrg94 — APPROVED** [review]
This looks great! I don't believe we have testing setup yet. Would you be interested in helping us set that up?

**Comment by izexi** [comment]
> This looks great! I don't believe we have testing setup yet. Would you be interested in helping us set that up?

Sure I could look into opening a PR for this sometime tomorrow, just to be clear are you referring to adding a `test_longest_palindrome_substring.py` test file to the `test/projects` directory?

**Comment by jrg94** [comment]
It's actually a somewhat complex process. There are three files that need to be added/updated:

- https://github.com/TheRenegadeCoder/sample-programs/blob/master/runner.py
- https://github.com/TheRenegadeCoder/sample-programs/blob/master/.glotter.yml
- https://github.com/TheRenegadeCoder/sample-programs/tree/master/test/projects

The first two are relatively straightforward. Then, you'd need to add a `test_longest_palindrome_substring.py` file which includes the actual tests.

**Comment by jrg94** [comment]
One thing worth mentioning is that we might want to add/change tests depending on what makes sense. Also, we need to decided on a file name. Longest Palindromic Substring is a bit long, but I'm not against using that straight up. That said, we've used LCS in the past for Longest Common Subsequence.

**Pull request merged**
