### PR TITLE
Roman numeral in Go

### LINKED ISSUE #539: Add Roman Numeral Conversion in Go
If this is your first time contributing, create the solution file in the appropriate directory and add the name of the program to the Sample Programs section of the language README. Then, create a new issue for its article like #30. Link this issue in the README and create a pull request when you're done.

### PR DESCRIPTION
**Pull request by clarkimusmax**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #539

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by Noah11012** [comment]
Can you please create an issue for article creation for roman numeral in Go?

**Comment by clarkimusmax** [comment]
> Can you please create an issue for article creation for roman numeral in Go?

Created:  https://github.com/TheRenegadeCoder/sample-programs/issues/616

Should the "Article needed" (#616) issue be linked in the Go README.md or the issue that the sample code is solving (#539)?  CONTRIBUTING.md doesn't specify.  If I can get this right, the third time could be the charm when I submit a PR for even/odd in go.  :-)

**Comment by Noah11012** [comment]
The link to the article creation. So, #616.

**Comment by clarkimusmax** [comment]
Ok, new commit should fix it

**Pull request merged**
