### PR TITLE
Added Hello World in V

### PR DESCRIPTION
**Pull request by ToyireuDev**

### CODE REVIEW

**Comment by jrg94** [comment]
Hey ToyireuDev! Is there anything you'd like to share about this code to give us a little more context?

**Comment by ToyireuDev** [comment]
It's the V programming language, a language close to go in syntax. the web site https://vlang.io

**Comment by jrg94** [comment]
Okay, I'm open to including it! There are some strange inconsistencies with the pull request I'd like to fix if possible. 

- [ ] First, I'd like to get the language name to be lowercase in the filepath.
- [ ] Second, I'd like to remove the txt file from the pull request.

Otherwise, this should be good to go!

**Comment by ToyireuDev** [comment]
ok

**Comment by rzuckerm** [comment]
@ToyireuDev It would also be nice if you included a `testinfo.yml` in the `archive/v/v` directory so that this sample program can be tested. I found a docker image [here](https://hub.docker.com/r/esolang/vlang). Please see the following [documentation](https://rzuckerm.github.io/glotter2/directory-level-configuration.html) for details on what goes into `testinfo.yml`. If you need help putting this together, please let me know.

**Review by rzuckerm — CHANGES_REQUESTED** [review]
@ToyireuDev It's been about a month since we heard from you. Please make the changes that @jrg94 suggested. If you do not plan to do so, please close this pull request. Thanks!

**Review by rzuckerm — APPROVED** [review]
@ToyireuDev Thanks for your submission. I cleaned it up and added tests. I encourage you to please read our [Contributing Guide](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.github/CONTRIBUTING.md) if you wish to contribute another submission.

**Pull request merged**
