### PR TITLE
Added Hello World in Astro

### LINKED ISSUE #1075: Add Hello World in Astro
See: https://github.com/astrolang/astro

### PR DESCRIPTION
**Pull request by asharma13524**
## I Am Adding a New Code Snippet in an Existing Language

I fixed #1075

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks great! We've recently begun changing our requirements, so we can't add this program as-is. Do you know if a Docker image exists for this language?

**Comment by asharma13524** [comment]
I'm not quite sure. I'm also new to the language. I do not believe so after googling and checking out their repository. I could be wrong though.

**Review by jrg94 — APPROVED** [review]
I took a peek! You're right. The language is in its alpha, and it hasn't been updated in awhile. I suspect there is no Docker image. We'll go ahead and add it in because I like having an archive of these sorts of languages.

**Comment by jrg94** [comment]
Whoops! We're missing the README. Any chance you'd want to put one of those together?

**Pull request merged**
