### PR TITLE
Added Comments to Runner.py Script

### PR DESCRIPTION
**Pull request by st1891**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
We always welcome these sort of changes, but I'm not sure these are needed. A further description may be helpful, though.

**Comment by st1891** [comment]
It's ok as your wish but I am beginners I only know about this I am very
excited to win tshirt and swag but it's ok

**Comment by jrg94** [comment]
No problem! I appreciate the submission. We'll close this out for now.

**Comment by st1891** [comment]
But how can I win tshirt

**Comment by jrg94** [comment]
There are a few ways. If you're a beginner, I recommend looking through docs and finding typos or other things that could be changed or written better. There's tons of that sort of stuff to look through in our docs repo: https://github.com/TheRenegadeCoder/sample-programs-website

**Pull request closed without merging**
