### PR TITLE
Added Reverse String in Odin

### PR DESCRIPTION
**Pull request by nallovint**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
  
  
## Other Notes

- I commented out main :: proc() as necessary to avoid conflicts when building - feel free to comment/uncomment as you need!

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-new-language]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-language
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sampleprograms.io/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by jrg94 — COMMENTED** [review]
Still running into this issue: `/src/reverse-string.odin(9:5) Syntax Error: Unknown tag directive used: 'reverse'`

I'm going to try updated the image to see if it pulls from a newer version of Odin.

**Review by jrg94 — CHANGES_REQUESTED** [review]
Life is good! Only one error:

```
=========================== short test summary info ============================
FAILED test/generated/test_reverse_string.py::test_reverse_string[odin/reverse-string.odin-No input] - AssertionError: assert 'Usage: please input a string' == ''
  + Usage: please input a string
=================== 1 failed, 416 passed in 97.81s (0:01:37) ===================
```

For whatever reason, we have this program setup to do nothing if the user provides no input.

**Review by rzuckerm — APPROVED** [review]
@jrg94 I think this should be fixed now

**Review by jrg94 — APPROVED** [review]
Nice work! Thanks for all the hard work.

**Pull request merged**
