### PR TITLE
Added Argparse Example in Python

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
This example adds basic argparse usage in a "hello world" format, demonstrating default values, named arguments and how to access them.

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is cool! Right now, this doesn't seem like a great fit for the repo. I'm not sure we could replicate this in other languages. Let me know what you think!

**Comment by CodeLongAndProsper90** [comment]
Hm, I know Dlang and C(++) can handle this, and I think that rust can too. I, personally, think that using argument parsing libraries is an essential skill, but I’m open to opinions.

**Comment by jrg94** [comment]
Good point! I'll let @auroq weigh in.

**Comment by CodeLongAndProsper90** [comment]
I can also create an example in Dlang, if that's a help.

**Pull request closed without merging**
