### PR TITLE
Added LCS in JavaScript

### LINKED ISSUE #1381: Add Longest Common Subsequence in JavaScript
See requirements: https://sample-programs.therenegadecoder.com/projects/longest-common-subsequence/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

### PR DESCRIPTION
**Pull request by imgovind**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #1381 

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[3]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/CODE_ARTICLE_TEMPLATE.md
[4]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/LANGUAGE_ARTICLE_TEMPLATE.md
[5]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md

### CODE REVIEW

**Comment by jrg94** [comment]
Actually, I had to rename this file because I don't think it's getting tested.

**Comment by jrg94** [comment]
Looks like it only failed for two cases:

```
_______________ test_lcs_valid[lcs.js-sample input same length] ________________
description = 'sample input same length'
in_params = '"1, 4, 5, 3, 15, 6" "1, 7, 4, 5, 11, 6"', expected = '1, 4, 5, 6'
lcs = Source(name: lcs, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/javascript)
    @project_test(ProjectType.LCS.key)
    @pytest.mark.parametrize(valid_permutations[0], valid_permutations[1],
                             ids=[p[0] for p in valid_permutations[1]])
    def test_lcs_valid(description, in_params, expected, lcs):
        actual = lcs.run(params=in_params)
>       assert clean_list(actual) == expected
E       assert 'Usage: pleas..., 2, 3, 4, 5"' == '1, 4, 5, 6'
E         - Usage: please provide two lists in the format "1, 2, 3, 4, 5"
E         + 1, 4, 5, 6
test/projects/test_lcs.py:52: AssertionError
_____________ test_lcs_valid[lcs.js-sample input different length] _____________
description = 'sample input different length'
in_params = '"1, 4, 8, 6, 9, 3, 15, 11, 6" "1, 7, 4, 5, 8, 11, 6"'
expected = '1, 4, 8, 11, 6'
lcs = Source(name: lcs, path: /home/travis/build/TheRenegadeCoder/sample-programs/archive/j/javascript)
    @project_test(ProjectType.LCS.key)
    @pytest.mark.parametrize(valid_permutations[0], valid_permutations[1],
                             ids=[p[0] for p in valid_permutations[1]])
    def test_lcs_valid(description, in_params, expected, lcs):
        actual = lcs.run(params=in_params)
>       assert clean_list(actual) == expected
E       assert 'Usage: pleas..., 2, 3, 4, 5"' == '1, 4, 8, 11, 6'
E         - Usage: please provide two lists in the format "1, 2, 3, 4, 5"
E         + 1, 4, 8, 11, 6
test/projects/test_lcs.py:52: AssertionError
```

**Comment by gpanneerselvam-prosper** [comment]
Yea I found that too, how can I run tests locally?

**Comment by gpanneerselvam-prosper** [comment]
Hey @jrg94 I am kind of at loss here as to what's going wrong, I am running on my local and it's giving the expected output. Any help?

**Comment by jrg94** [comment]
Good question! You can take a look at the new testing section in our contributing doc: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests

There are two tests still failing. Does your solution work for the following tests?

- in_params = '"1, 4, 5, 3, 15, 6" "1, 7, 4, 5, 11, 6"', expected = '1, 4, 5, 6'
- in_params = '"1, 4, 8, 6, 9, 3, 15, 11, 6" "1, 7, 4, 5, 8, 11, 6"', expected = '1, 4, 8, 11, 6'

**Comment by imgovind** [comment]
Screenshot 2019-10-23 22 20 02

**Comment by jrg94** [comment]
Whoops! I realize the issue now. Your program is expecting a single input (`arv[2]`). There's actually two pieces of input (`argv[2]` and `argv[3]`) for each string.

**Pull request closed without merging**
