### PR TITLE
Added Grammar example in Perl6

### PR DESCRIPTION
**Pull request by Couraxe**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Added the exemplary Grammar code from the Raku programming language's homepage.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by McSinyx** [comment]
IMHO we should move the Raku archive to `r/raku` since the name Perl 6 is no longer used.

**Comment by Couraxe** [comment]
@McSinyx I concur, "Perl 6" has been deprecated for a while now.

**Review by jrg94 — CHANGES_REQUESTED** [review]
This a cool idea, but we don't currently support it. We'd be happy to get some help with Perl6 in general, though. Here's the list of supported projects if you're interested: https://sample-programs.therenegadecoder.com/projects/

**Comment by jrg94** [comment]
Also, I'm totally cool with moving this folder to Raku if that's makes sense.

**Comment by Couraxe** [comment]
@jrg94 Totally! I'll them be adding more Raku examples.

**Pull request closed without merging**
