### PR TITLE
Added Palindrome Word in PHP

### PR DESCRIPTION
**Pull request by samgan-khan**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [ ] I names the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[3]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/CODE_ARTICLE_TEMPLATE.md
[4]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/LANGUAGE_ARTICLE_TEMPLATE.md
[5]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md

### CODE REVIEW

**Comment by jrg94** [comment]
This looks awesome, but I don't think we currently have [any formal description of this project](https://sample-programs.therenegadecoder.com/projects/). I'm happy to merge this in, but I'd like to get a nice specification put together as well.

**Comment by samgan-khan** [comment]
hey, well I didn't know about the project thing but palindrome program is pretty common. So I guess we should have one as a project.

**Comment by jrg94** [comment]
No sweat! We just like to have some form of specification for the projects, so we can get some common solutions across the languages (and, so we can test them!). 

If you want to help write up the description, we have a [generic template](https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md) that you might find helpful. Then, you'd want to create a new folder for the project in the [projects documentation directory](https://github.com/TheRenegadeCoder/sample-programs/tree/master/docs/projects) and place the index.html file there.

**Comment by samgan-khan** [comment]
ok got it. Next time ill do that in case I am going off the projects. Thanks mate.

**Pull request merged**
