### PR TITLE
Added Hello World in Flix

### LINKED ISSUE #180: Add Hello World in Flix
Source: https://github.com/flix/flix

### PR DESCRIPTION
**Pull request by JavaVista**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.
  
## I Am Adding a New Code Snippet in a New Language

- [X] I fixed #180 
- [X] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format

- [X] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [X] I added the sample program name to the README
  - [X] I added fun facts (i.e. debut developer, typing, etc.)
  - [X] I added reference link(s) to the README
  - [X] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])
  

## I Am Adding New Tests for a Project

- [X] I named the pull request using `Add {PROJECT} tests` format
- [X] I verified the project exists on the [Sample Programs Project List][sample-programs-project-list]

## Other Notes

Operating System: Windows
Editor used: VS Code
VS Extension used to run language: [Flix for Visual Studio Code](https://github.com/flix/vscode-flix)

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is really awesome! Thanks for going through the effort of generating this README as well. Recently, we changed our requirements, so we unfortunately cannot merge this as-is. Do you know if this language has a Docker image?

**Comment by JavaVista** [comment]
> This is really awesome! Thanks for going through the effort of generating this README as well. Recently, we changed our requirements, so we unfortunately cannot merge this as-is. Do you know if this language has a Docker image?

No at this moment since it it still alpha stage. But thank you for making this a nice learning experience.

**Comment by jrg94** [comment]
How about this? Can you move the files to the language folder? In other words, removed the "hello-world" folder. Then, we'll merge this.

**Comment by JavaVista** [comment]
Removed the hello world folder and moved files to the root of the language folder. Happy Hacktoberfest!

**Pull request merged**
