### PR TITLE
Added Anagram in Python

### LINKED ISSUE #1161: Add Anagram in Python

### PR DESCRIPTION
**Pull request by jeffin07**
- [ ] I fixed #1161 

Added python script for #1161 
`python3 anagram.py`

Which takes two inputs from the user and return true if anagram else flase

#### Files change
1. anagram.py in python 
2. README.md in python

### CODE REVIEW

**Comment by jeffin07** [comment]
@jrg94  But  #1162  already has a modified readme. Is there any other documentation other than that for python

**Comment by jrg94** [comment]
Yeah! We like to put together a project page for each new project: https://sample-programs.therenegadecoder.com/projects/

**Comment by jeffin07** [comment]
@jrg94 okay i get it. So the documentation you're saying is this [Doc](https://github.com/TheRenegadeCoder/sample-programs/tree/master/docs/projects) right ?

**Comment by jrg94** [comment]
Yeah, exactly!

**Comment by jeffin07** [comment]
@jrg94 When i looked into that each one has different structure means some of them has _posts folder some don't so can you tell me which to follow

**Comment by jrg94** [comment]
Yeah, @jeffin07 ! If the _posts folder is missing, you can add it. It comes from Jekyll if you're curious about the actual framework. 

That said, all you need for a project page is an index file.

**Comment by jrg94** [comment]
Closing. See discussion on #1162.

**Pull request closed without merging**
