### PR TITLE
Added Factorial in Ruby

### PR DESCRIPTION
**Pull request by edersonferreira**
- Adding fatorial code example to Ruby directory.
- Adding fatorial in Ruby README.md

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks good! Any chance you could rename the file to "factorial.rb"? I think travis should then test it automatically.

**Comment by edersonferreira** [comment]
I renamed it. now it is ok!

**Review by jrg94 — CHANGES_REQUESTED** [review]
Awesome! Can you double check the requirements here: https://sample-programs.therenegadecoder.com/projects/factorial/

You can check here to see which tests failed: https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/187515770

**Comment by edersonferreira** [comment]
Now I added some checks to the value

**Pull request closed without merging**
