### PR TITLE
Added Maximum Subarray in Python

### LINKED ISSUE #2054: Add Kadane's Algorithm in Python
Kadane's algorithm is a useful algorithm that, given an array, finds the largest sum of a contiguous subarray

### PR DESCRIPTION
**Pull request by Senpai1199**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #2054 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
- [x] I added the sample program name to the README
- [ ] I added fun facts (i.e. debut developer, typing, etc.)
- [x] I added reference link(s) to the README
- [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [x] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

### CODE REVIEW

**Comment by Senpai1199** [comment]
@jrg94 Could you review this?

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks fine! Just holding off for now as this needs to be documented before we can include it.

**Comment by Senpai1199** [comment]
@jrg94 Could you tell me which docs do I need to add?

**Comment by Senpai1199** [comment]
@jrg94 I've added the docs for Kadane's Algorithm in the sample-programs-website repository.

Here is my PR for the same on that repository: https://github.com/TheRenegadeCoder/sample-programs-website/pull/340

**Review by jrg94 — APPROVED** [review]
Looks great! As far as I know, this still needs testing. That said, the code looks like it does what we have documented. I can fix things up once testing is added.

**Pull request merged**
