### PR TITLE
Added Selection Sort in C#

### LINKED ISSUE #916: Add Selection Sort in C#

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #916 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by auroq** [comment]
This one turned out to be really cool in C#. I like this implementation. I probably ought to rewrite python to be more like this. While I do like the recursive solution with an accumulator (as I did in haskell and python), I don't think it turns out as clean in python as in haskell. This solution on the other had would be really clean in python.

**Comment by jrg94** [comment]
This solution is wild. Instead of building a list, it looks like you create an enumerator/iterator and use that to spit out your sorted list. It's surprisingly elegant.

**Comment by jrg94** [comment]
C# just eclipsed C. I imagine @chrboe will be upset.

**Comment by auroq** [comment]
Haha. I'm happy. I was hoping it would be haskell that did it, but I guess it's too efficient.

**Pull request merged**
