### PR TITLE
Renamed and Isolated Bugs in Even Odd in Bash

### LINKED ISSUE #1817: `even-odd.sh` does not get executed by test runner
Hello.

I noticed that [`evenodd.sh`](https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/b/bash/odd-even.sh) wasn't being run by [the continuous build service](https://travis-ci.com/TheRenegadeCoder/sample-programs)--that is, it isn't being run through the tests.

Then I noticed that it wasn't using [the "hyphen" naming scheme](https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#source-files).

I figured that there was a causal relationship between those two facts, so I [renamed it](https://github.com/TheRenegadeCoder/sample-programs/pull/1815/commits/9c25f902738cb8bcccc7980fca61fe408137cb59).

Well, the tests still aren't running for that `even-odd.sh` script.  I looked around, but I wasn't able to figure out why not.

### PR DESCRIPTION
**Pull request by daveloyall**
Fixes #1817

### CODE REVIEW

**Comment by daveloyall** [comment]
oh that's AWESOME.  Sincerely.  The code was in there, but the tests weren't running.  This change of mine got the tests running.  And they FAIL.  The system works! :)

See https://travis-ci.com/TheRenegadeCoder/sample-programs/jobs/250643589#L475-L479

**Comment by daveloyall** [comment]
Still got a failure on the negative number tests.

**Comment by jrg94** [comment]
You're right. I'm not sure how to fix that.

**Comment by jrg94** [comment]
So, I updated the solution, and it works on Jdoodle, but not here...

**Comment by jrg94** [comment]
Whoops! I have the tests backward. I should allow negatives...

**Pull request merged**
