### PR TITLE
Add remove-whitespace in Javascript

### PR DESCRIPTION
**Pull request by khalby786**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [ ] I fixed #your-issue-number-here
- [X] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [X] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [X] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [X] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

  

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by khalby786** [comment]
@jrg94, what do I need to do to remove the "need docs" badge? Where do I add documentation for code?

**Comment by jrg94** [comment]
We don't currently have this documented: https://sample-programs.therenegadecoder.com/projects/

You can head over here to get it documented: https://github.com/TheRenegadeCoder/sample-programs-website

**Comment by khalby786** [comment]
Sure! Will do the documentations and will also do the tests!

**Comment by khalby786** [comment]
The tests seem to be in Python, where do I add tests?

**Comment by khalby786** [comment]
Actually, I would like to close this pull request.

**Comment by jrg94** [comment]
Sounds good! Let me know if you want to help fill out some of these things.

**Pull request closed without merging**
