### PR TITLE
Add Rot13 in Brainfuck

### LINKED ISSUE #3474: Add Rot13 in Brainfuck
To request a new code snippet, please fill out the following:

Project name: Rot13
Project link: https://sampleprograms.io/projects/rot13
Language: Brainfuck

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

### PR DESCRIPTION
**Pull request by jt-pandey**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #3474
- [x] I named the pull request using `Add Rot13 in Brainfuck` format

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-new-language]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-language
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sampleprograms.io/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by rzuckerm — CHANGES_REQUESTED** [review]
Something is causing [this job](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/6537693895/job/17752793832#step:6:1999) to hang. I see the test for the "sample input lowercase" start, but I never see it finish. See the "Testing" section of [this](https://sampleprograms.io/projects/rot13/) for details on what is tested.

**Comment by jt-pandey** [comment]
I used the script as mentioned in the glotter2 repo (redraiment/brainfuck), hope it works now.

**Comment by rzuckerm** [comment]
> I used the script as mentioned in the glotter2 repo (redraiment/brainfuck), hope it works now.

I ran this locally, and it is locking up. I tried running it inside a docker container like this:
```console
$ docker run -it --rm -v $(pwd)/archive/b/brainfuck:/local --entrypoint="" redraiment/brainfuck:latest sh
/local # echo "Hello" | brainfuck -s rot13.bf
Uryyb
^C
/local # echo "HELLO" | brainfuck -s rot13.bf
URYYB
^C
```

It also looks like the invalid tests are not being addressed (I would expect an error condition for these):
```console
/local # echo -n "" | brainfuck -s rot13.bf 
^C
/local # echo "" | brainfuck -s rot13.bf 

^C
```

I verified that the interpreter is in fact working for standard input:
```console
/local # echo "HELLO" | brainfuck -s reverse-string.bf 

OLLEH
```

**Comment by rzuckerm** [comment]
Closing due to lack of activity

**Review by rzuckerm — APPROVED** [review]
@jt-pandey Thanks for you submission. I finally got a check to revisit this PR. The implementation of Brainfuck that we use returns 0 when there is no character, so the approach you were using to detect end of input wasn't working. Instead of 0, you were getting 1. Also, I added some code to detect when a non-zero character was detected (0 if detected, else 1). I used that to display the error message if no non-zero characters are detected. I got the character generator from [this site](https://copy.sh/brainfuck/text.html).

**Pull request merged**
