### PR TITLE
Added Banker's Algorithm in Python

### LINKED ISSUE #2021: Add Banker's Algorithm in Python
Please link the documentation for this project in the space below (note: don't 
forget to remove the backticks). To find the existing list of supported projects, 
[look here][1]:

`[Project Link](https://repl.it/@MihirMahajani/Bankers-Algorithm)`

If this code snippet adds a new language to the repo, please provide a link(s) to the 
language documentation to prove its existence in the space below. Feel free to omit
this section otherwise.

`[Project Documentation](https://example-lang.com)`

[1]: https://sample-programs.therenegadecoder.com/projects/

### PR DESCRIPTION
**Pull request by Mihir2527**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #2021 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by Mihir2527** [comment]
Please review my pull request and do tell me if any changes are needed

**Comment by Mihir2527** [comment]
Please review my PR

**Review by jrg94 — CHANGES_REQUESTED** [review]
Very cool idea! We don't currently support this program, but we're open to including it if we can get it documented.

**Comment by Mihir2527** [comment]
Sure!! Where can I get the format for the documentation and where should I add it ?

**Comment by jrg94** [comment]
Good question. We document everything here: https://github.com/TheRenegadeCoder/sample-programs-website

Here's a template to help you get started: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md

**Pull request closed without merging**
