### PR TITLE
Added Happy Birthday in Ruby

### PR DESCRIPTION
**Pull request by Solis1**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format

### Testing

- [x] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes
In order for the script to work, two parameters have to be entered: a name and the user's date of birth. If the current day matches that date, the script will display a happy birthday greeting but simply wish you a good day. Example of how to run the script:

```
ruby happy_birthday.rb Ramiro 05/10/1997
```

It will take the day and month of the birthday entered and compare them against the current day to determine if it is a normal greeting or a birthday greeting

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Interesting idea! Pretty similar to Hello World but with a little but of input. Any chance we could get this documented?

**Comment by Solis1** [comment]
> Interesting idea! Pretty similar to Hello World but with a little but of input. Any chance we could get this documented?

Yeah where do you put the documentation? i add it in the readme the script and also add it some comments in the code

**Comment by Solis1** [comment]
> Interesting idea! Pretty similar to Hello World but with a little but of input. Any chance we could get this documented?

I add it some notes in the pr description, to describe how it works the script

**Comment by jrg94** [comment]
We usually try to document these kinds of programs here: https://sample-programs.therenegadecoder.com/projects/

That way, folks can replicate them in other languages.

**Pull request closed without merging**
