### PR TITLE
Added Sleep Sort in Dart

### LINKED ISSUE #1205: Add Sleep Sort in Dart
If possible, please provide a link(s) to the language documentation to prove its existence:

- https://dart.dev/guides

If possible, please provide a code snippet of Hello World in the language:

```dart
void main() => print('Hello, World!');
...
````

### PR DESCRIPTION
**Pull request by agilob**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed  #1205

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x= I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [x] I followed the applicable article template
  - [x] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [x] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [x] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [x] I names the pull request using `Added/Updated <Language>/<Project> Testing` format
- [x] I followed the testinfo template, if applicable

### CODE REVIEW

**Comment by jrg94** [comment]
Hey @agilob! We don't currently support Sleep Sort, but we'd be happy to include it in the collection. Would you want to put together a little documentation for this program, so we can standardize it over other languages? See [projects list](https://sample-programs.therenegadecoder.com/projects/) for more info.

**Comment by agilob** [comment]
Ah right, there it is, I couldn't find the list of the sample projects, it's here https://github.com/TheRenegadeCoder/sample-programs/tree/master/docs/projects ;) I'll update this tomorrow

**Comment by jrg94** [comment]
@agilob, any news on the update?

**Comment by agilob** [comment]
updated

**Pull request merged**
