### PR TITLE
Added Collatz in Python

### LINKED ISSUE #2101: Add Collatz in Python
This issue requests the addition of a snippet of code to calculate the sequence of Collatz.

[Project](https://en.wikipedia.org/wiki/Collatz_conjecture)

### PR DESCRIPTION
**Pull request by noemi3**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #2101 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Added the script that retur a list of number of Collatz sequence. 

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is a cool idea! Any chance we could get it documented?

**Comment by noemi3** [comment]
Hi @jrg94, I added a docstring to my file. Is this ok?

**Comment by jrg94** [comment]
That's fine! What we mean by document is we need an article to be written over here: https://github.com/TheRenegadeCoder/sample-programs-website

That way, other languages can have the same program replicated.

**Comment by noemi3** [comment]
You can find the documentation on wikipedia, at this [link ](https://it.wikipedia.org/wiki/Congettura_di_Collatz). I think isn't interesting copy the entire page of wikipedia.

**Comment by jrg94** [comment]
Sure! But our documentation follows a strict template: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md

We need to get the testing section documented, so other folks can duplicate this.

**Pull request closed without merging**
