### PR TITLE
Recursive Fibonacci with Cache in Rust language

### PR DESCRIPTION
**Pull request by vfrico**
Fast implementation of recursive fibonacci that uses an integer array to
store precomputed values

This is relevant because shows how to share an array with other
functions in rust as a mutable array.

Note: uint128 is unable to hold values greater than fib(185)

Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

[Created article](https://gist.github.com/vfrico/b790e472b5d19112b2b66fd22104ca90)

## Please Complete the Following

- [x] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [ ] I fixed #your-issue-number-here

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by Noah11012** [comment]
I commend you on writing a gist to explain your code but that's not how it exactly works. You create an issue for article creation then link to it in the README.md file then when you have the time, write up an article on [The Renegade Coder](https://therenegadecoder.com)

**Comment by jrg94** [comment]
Also, isn't fibonacci already in the repo? I haven't really thought much about duplicate programs in different styles/algoriths/etc.

**Comment by Noah11012** [comment]
Yes, a Fibonacci implementation is already made in Rust. However, this is a better implementation because it uses memoization to cache already calculated values. So, this is a faster implementation than the previous one.

**Comment by jrg94** [comment]
Is the intent to have this solution replace the current one?

**Comment by Noah11012** [comment]
Not sure. Maybe it would be a good idea for people who never implemented a Fibonacci sequence generator to see an inefficient implementation and a better implementation using memoization. That way they can contrast between the two. Perhaps, it is actually better to replace the original one with the better one so that we do not encourage inefficient algorithms.

**Comment by jrg94** [comment]
I'm not sure I'm comfortable with having multiple solutions just yet. That would required a pretty hefty rework of the repo and the article series. 

The short term solution would be to create a folder just for fibonacci solutions. But, that would cause a chain reaction of changes in the repo as well as the articles. We'll have to chat about it.

**Comment by vfrico** [comment]
I've done the changes requested.

I know it is an algorithm which was already proposed. But I think that this version introduces the concept of arrays creation and reference pointers which can be relevant for someone looking for a sample program in rust.

**Comment by Noah11012** [comment]
I'm not sure if we should replace the old one. Yes, your implementation is better, but we also strive for simplicity as much as we can. The memoization might get in the way. Then after all, maybe we should encourage efficient algorithms in addition to the principle of keeping it simple.

**Comment by jrg94** [comment]
I have no problem with including this solution to be honest. The issue I have is more so with scalability of this repo. If we allow an alternate solution, we'll have to allow all alternate solutions (within reason). That's fine! But, I have two questions:

1. How will we handle articles moving forward? Currently, they're organized by problem, so will alternate solutions require alternate articles? Or, will we have to edit current articles to support the new solution? 
2. How will we handle repo organization? Do we leave problems open to alternate solutions and create subfolders for every problem with multiple solutions? I'm personally fine with that, but we'll need to update the wiki generator repo to compensate for this change.

**Comment by Noah11012** [comment]
We could show each alternate version in the article. Show the simplest version first then show the better versions. This is probably not the best way to do it because everytime a new version is created then we have to update the appropriate article.

Now about the restructuring of the repository. I do like the idea of having subfolders for each problem. And while someone will have to update the wiki generator, as you mentioned, that is far from our problem with this issue. 

The way articles will be made/changed is a bigger problem and a potential, though not optimal, is to keep creating articles for the first/simplest version of the problem then have [Gist](https://gist.github.com)s for the other versions.

**Comment by jrg94** [comment]
Currently, we already have problems with solutions being updated and articles not changing. That's a problem that will likely never go away unless I recruit a few a editors. With that said, I think I'm happy with having really large articles (Google likes that better anyway). I'll just have to figure out how to add co-authors to articles--I'm sure that's easy in WordPress. 

The issue then becomes deciding where to draw the line on alternate vs. improved solutions. For example, I would like to keep both the original fibonacci and this fibonacci in the repo since they are just different solutions to the same problem. Improved solutions should come in as changes on existing solutions--rather than as new files. 

Sound like a plan? If so, I'll draft up the changes to the contributing doc. We'll then ask @vfrico to place their solution in a subfolder titled `fibonacci` alongside your solution. I don't think an article exists yet for either of these solutions, so the either one of you could begin writing it if you're interested.

**Comment by Noah11012** [comment]
Sounds like a good plan to me. I haven't (unfortunately) written any articles for a while so, in the near future, I plan to write an article for my solution. If @vfrico wants to, he can write an article for his memoization implementation.

**Comment by jrg94** [comment]
Ugh, there doesn't seem to be a nice way to indicate co-authorship through WordPress. As of now, I'm looking back into opening up the articles for editing here on GitHub (see the [Writing on GitHub plugin](https://github.com/litefeel/writing-on-github)). Sadly, it doesn't serve my needs to enable collaborative article editing.

**Comment by jrg94** [comment]
Let's move ahead with the repo restructuring. I'll go ahead and start tackling the fix for the wiki generator, and I'll open a new discussion on #242. I don't think the article problem is a huge now problem. I think I can try to tackle it over winter break.

**Comment by jrg94** [comment]
Alright, we've made a lot of changes to the repo to support this change, but I still want to hold off on merging this until we get the wiki generator setup (or, alternatively, move the wiki into GitHub pages).

**Comment by jrg94** [comment]
I'm going to close this for now. We're just not at a point in this repo where it makes sense to start supporting multiple solutions to the same problem.

I'd be happy to support it if there's some community backing, but we have our hands full with the scope of the project already.

**Pull request closed without merging**
