### PR TITLE
Fibonacci in Haskell

### LINKED ISSUE #543: Add Fibonacci in Haskell
If this is your first time contributing, create the solution file in the appropriate directory and add the name of the program to the Sample Programs section of the language README. Then, create a new issue for its article like #30. Link this issue in the README and create a pull request when you're done.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by PanagiotisGeorgiadis**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #543 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
Looks great! How would I go about testing this? I tried JDoodle, but I get the following error: 

```
jdoodle.hs:11:1: error:
    * Couldn't match expected type `IO t0'
                  with actual type `Int -> [Int]'
    * Probable cause: `main' is applied to too few arguments
      In the expression: main
      When checking the type of the IO action `main'
   |
11 | main n = fibonacciSequence n
   | ^
```

**Comment by PanagiotisGeorgiadis** [comment]
I wasn't completely aware on how you'd go about compiling it! Give me 5 minutes and I should make another commit to make it JDoodle ready :)

**Comment by PanagiotisGeorgiadis** [comment]
If you want you can give the updated code a try :)

**Comment by PanagiotisGeorgiadis** [comment]
Of course!

**Comment by PanagiotisGeorgiadis** [comment]
Updated the solution in order to accept the number of Fibonacci elements required as a command line argument.

**Comment by Noah11012** [comment]
Tested your updated version and it works! Even though I do have write access to this repository, I want to make sure that @jrg94 doesn't mind me merging this code into the master.

**Comment by jrg94** [comment]
It’s all good! 😄 you’re welcome to merge this. That’s why I added you to core!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Noah11012** [comment]
Merged!

**Pull request merged**
