### PR TITLE
Add Test for Quine

### PR DESCRIPTION
**Pull request by auroq**
I like how this one turned out. Much more straight forward than I expected when starting this project. Creating an object containing all source metadata made it come out cleanly.

### CODE REVIEW

**Comment by auroq** [comment]
Btw, @jrg94, what IDE do you generally use? I use mostly jetbrains stuff myself, and it makes running these tests really straightforward. I have a run configuration for each test module and one that runs all.

**Comment by jrg94** [comment]
I use a lot of IDEs.... But, for Python mainly PyCharm. I think that's jetbrains.

**Comment by auroq** [comment]
> I use a lot of IDEs.... But, for Python mainly PyCharm. I think that's jetbrains.

Ya, that's jetbrains. Since my job now allows me to use almost exclusively linux, I now just use vim and whichever jetbrains IDE is applicable to the language.

**Comment by jrg94** [comment]
Can you help me set up a run configuration for this? I believe it's running, but I guess I need docker on my machine for this to actually work. I downloaded Docker, and now I get a new fun error:

```
F
projects\test_baklava.py:14 (test_baklava[baklava.sh])
self = <docker.api.client.APIClient object at 0x04A00510>
response = <Response [500]>

    def _raise_for_status(self, response):
        """Raises stored :class:`APIError`, if one occurred."""
        try:
>           response.raise_for_status()

C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\client.py:261: 
```

**Comment by auroq** [comment]
That snippet doesn't tell me

**Comment by auroq** [comment]
That snippet doesn't tell me much other than you're getting a 500 error. There's two docker commands being run `docker pull` and `docker run`. My guess is you're either not able to connect to the docker daemon on your machine or you're not able to connect docker hub.

Can you try doing a `docker pull python:3.7` from whatever cli you use on your machine and let me know if that works. Try it both with and without administrative privileges.

**Comment by jrg94** [comment]
Alright, here's the result of no admin privileges:

```
C:\Users\Jerem>docker pull python:3.7
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://192.168.99.100:2376/v1.37/info: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.). Using system default: https://index.docker.io/v1/
error during connect: Post https://192.168.99.100:2376/v1.37/images/create?fromImage=python&tag=3.7: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

And, it's the same from admin:

```
C:\WINDOWS\system32>docker pull python:3.7
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://192.168.99.100:2376/v1.37/info: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.). Using system default: https://index.docker.io/v1/
error during connect: Post https://192.168.99.100:2376/v1.37/images/create?fromImage=python&tag=3.7: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by auroq** [comment]
Judging from your windows path earlier, I assume you're using docker desktop. Can you ensure the docker engine is running? It should appear in your system tray on the taskbar.

https://docs.docker.com/docker-for-windows/#docker-settings-dialog

**Comment by jrg94** [comment]
Ahh, yes. Now, it works without admin:

```
C:\Users\Jerem>docker pull python:3.7
3.7: Pulling from library/python
Digest: sha256:c32b1a9fb8a0dc212c33ef1d492231c513fa326b4dae6dae7534491c857af88a
Status: Image is up to date for python:3.7
```

**Comment by auroq** [comment]
Cool. Try running the tests again. It might take a while the first time because it has to pull the images.
If you want to speed it up you can do `docker pull {IMAGE}:{TAG}` for each language we have setup where IMAGE and TAG can be found in the testinfo.yml

**Comment by jrg94** [comment]
For some reason, the pytest setup still isn't working. It's like properly iterating over the test, but I'm still getting the 500 error:

```
F
projects\test_baklava.py:14 (test_baklava[baklava.sh])
self = <docker.api.client.APIClient object at 0x04E30450>
response = <Response [500]>

    def _raise_for_status(self, response):
        """Raises stored :class:`APIError`, if one occurred."""
        try:
>           response.raise_for_status()

C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\client.py:261: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Response [500]>

    def raise_for_status(self):
        """Raises stored :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ''
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
            # isn't utf-8, we fall back to iso-8859-1 for all other
            # encodings. (See PR #3538)
            try:
                reason = self.reason.decode('utf-8')
            except UnicodeDecodeError:
                reason = self.reason.decode('iso-8859-1')
        else:
            reason = self.reason
    
        if 400 <= self.status_code < 500:
            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        elif 500 <= self.status_code < 600:
            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://192.168.99.100:2376/v1.35/containers/create

C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\requests\models.py:940: HTTPError

During handling of the above exception, another exception occurred:

docker_client = <docker.client.DockerClient object at 0x04E303D0>
baklava = <test.source.Source object at 0x04CD9C10>

    def test_baklava(docker_client, baklava):
        expected = """          *
             ***
            *****
           *******
          *********
         ***********
        *************
       ***************
      *****************
     *******************
    *********************
     *******************
      *****************
       ***************
        *************
         ***********
          *********
           *******
            *****
             ***
              *
    """
        expected_lines = expected.split(os.linesep)
>       actual = baklava.run(docker_client)

projects\test_baklava.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
source.py:74: in run
    expect_error=expect_error
source.py:108: in _run_container
    volumes=volume_info)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\models\containers.py:785: in run
    detach=detach, **kwargs)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\models\containers.py:843: in create
    resp = self.client.api.create_container(**create_kwargs)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\container.py:427: in create_container
    return self.create_container_from_config(config, name)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\container.py:438: in create_container_from_config
    return self._result(res, True)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\client.py:267: in _result
    self._raise_for_status(response)
C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\api\client.py:263: in _raise_for_status
    raise create_api_error_from_http_exception(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

e = HTTPError('500 Server Error: Internal Server Error for url: https://192.168.99.100:2376/v1.35/containers/create',)

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid volume specification: 'C:\Users\Jerem\AppData\Local\Temp\tmp6yzsgil1:/src:rw'")

C:\Users\Jerem\PycharmProjects\test\venv\lib\site-packages\docker\errors.py:31: APIError
```

**Comment by auroq** [comment]
Can you open a python REPL in the environment that has the requirements-test.txt installed and do

>>> import docker
>>> docker.from_env().images.pull('python', '3.7')
<Image: 'python:3.7'>
>>>

**Comment by jrg94** [comment]
Oddly enough, that works. hahaha

**Comment by jrg94** [comment]
What's my run configuration supposed to look like? I just have it pointing at the init in the test folder.

**Comment by auroq** [comment]
```
>>> client = docker.from_env()
>>> image = client.images.pull('python', '3.7')
>>> client.containers.run(image=image, working_dir='/src', remove=True, detach=False)
b''
>>> 
```

**Comment by auroq** [comment]
here's the one I use for baklava
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run Tests: Baklava" type="tests" factoryName="py.test">
    <module name="sample-programs" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="PARENT_ENVS" value="true" />
    <option name="SDK_HOME" value="" />
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$/test" />
    <option name="IS_MODULE_SDK" value="true" />
    <option name="ADD_CONTENT_ROOTS" value="true" />
    <option name="ADD_SOURCE_ROOTS" value="true" />
    <EXTENSION ID="PythonCoverageRunConfigurationExtension" runner="coverage.py" />
    <option name="_new_keywords" value="&quot;&quot;" />
    <option name="_new_additionalArguments" value="&quot;-vv&quot;" />
    <option name="_new_target" value="&quot;projects.test_baklava&quot;" />
    <option name="_new_targetType" value="&quot;PYTHON&quot;" />
    <method v="2" />
  </configuration>
</component>
```

**Comment by jrg94** [comment]
I'll try both of these later tonight. Thanks again for your help.

**Pull request merged**
