### PR TITLE
Add Sleep Sort in F#

### LINKED ISSUE #2446: Add Sleep Sort in F#
Project name: 
Project link: https://sample-programs.therenegadecoder.com/projects/sleep-sort/
Language:  F#

### PR DESCRIPTION
**Pull request by renato04**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #2446 
- [x] I named the pull request using `Add Sleep Sort in F#` format
  
  
## I Am Adding a New Code Snippet in a New Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
  

## I Am Adding New Tests for a Project

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} tests` format
- [ ] I verified the project exists on the [Sample Programs Project List][sample-programs-project-list]
- [ ] I added tests for every test case in the Testing table of the project description for the given project. (See [contributing documentation][contributing-tests-in-detail])

## I Am Adding New Tests for a Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {LANGUAGE} tests` format\
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
- [ ] I verified all tests are passing

  
## I Am Modifying an Existing Code Snippet or Existing Tests

- [ ] I fixed #your-issue-number-here
- [ ] I have read about modifying existing code snippets or tests in the [contributing documentation][contributing-modifications]
- [ ] I have explained why this modification is _necessary_ either in the issue linked above or in the notes below
- [ ] I named the pull request using `Modify {PROJECT} {tests} in {LANGUAGE}` format

## Other Notes

Add notes here...

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by renato04** [comment]
What do i have to do to fix the PR?

**Comment by jrg94** [comment]
Here are the errors:

```
==================================== ERRORS ====================================
______ ERROR at setup of test_sleep_sort_valid[SleepSort.fs-sample input] ______

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_ ERROR at setup of test_sleep_sort_valid[SleepSort.fs-sample input: with duplicate] _

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_ ERROR at setup of test_sleep_sort_valid[SleepSort.fs-sample input: already sorted] _

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_ ERROR at setup of test_sleep_sort_valid[SleepSort.fs-sample input: reverse sorted] _

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_______ ERROR at setup of test_sleep_sort_invalid[SleepSort.fs-no input] _______

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_____ ERROR at setup of test_sleep_sort_invalid[SleepSort.fs-empty input] ______

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_ ERROR at setup of test_sleep_sort_invalid[SleepSort.fs-invalid input: not a list] _

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
_ ERROR at setup of test_sleep_sort_invalid[SleepSort.fs-invalid input: wrong format] _

request = <SubRequest 'sleep_sort' for <Function test_sleep_sort_valid[SleepSort.fs-sample input]>>

    @project_fixture(ProjectType.SleepSort.key)
    def sleep_sort(request):
>       request.param.build()

test/projects/sorting/test_sleep_sort.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Source(name: SleepSort, path: /home/runner/work/sample-programs/sample-programs/archive/f/f-sharp)
params = ''

    def build(self, params=''):
        if self.test_info.container_info.build is not None:
            command = f'{self.test_info.container_info.build} {params}'
            result = self._container_exec(command)
            if result[0] != 0:
>               raise RuntimeError(f'unable to build using cmd "{self.test_info.container_info.build} {params}":\n'
                                   f'{result[1].decode("utf-8")}')
E               RuntimeError: unable to build using cmd "fsharpc --standalone -o SleepSort SleepSort.fs ":
E               Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
E               Copyright (c) Microsoft Corporation. All Rights Reserved.
E               
E               /src/SleepSort.fs(5,9): error FS0039: The value, namespace, type or module 'Console' is not defined. Maybe you want one of the following:
E                  Consts
E                  Control
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'    
E               
E               /src/SleepSort.fs(13,5): error FS0001: This expression was expected to have type
E                   'int'    
E               but here has type
E                   'unit'

/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/glotter/source.py:58: RuntimeError
================== 1879 passed, 8 error in 787.29s (0:13:07) ===================
```

I don't know enough about F# to provide further support, but it looks like there's an issue with your usage of Console.

**Comment by renato04** [comment]
Is this a python code calling F# method?

**Comment by jrg94** [comment]
Sort of! It's Python running a Docker image which runs F#.

**Comment by renato04** [comment]
Where is this test?
For me run it local

**Comment by renato04** [comment]
I think I fixed it

**Review by jrg94 — CHANGES_REQUESTED** [review]
It looks like the updated program crashes. I might recommend taking a peek at the testing section of the contributing doc. It should give details on how to run the tests locally.

**Pull request closed without merging**
