### PR TITLE
Added Capitalize in CoffeeScript

### LINKED ISSUE #1325: Add Capitalize in CoffeeScript
See requirements: https://sample-programs.therenegadecoder.com/projects/capitalize/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/coffeescript

### PR DESCRIPTION
**Pull request by Saoskia**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1325 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Added the Capitalize first letter program in CoffeeScript.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks good! Is there any chance we could get this program to pull from the command line?

**Comment by Saoskia** [comment]
Done 👍

**Review by jrg94 — APPROVED** [review]
Alright, this looks good! I think we may need to revisit it when we add testing, but otherwise nice work.

**Comment by jrg94** [comment]
Hey @Saoskia! If you enjoyed contributing to this project and would like to make sure that it continues to be maintained, we can always use your support at The Renegade Coder. Here are some ways you can help out:

- Subscribe to the [monthly newsletter](https://newsletter.therenegadecoder.com/)
- Become a [patron](https://www.patreon.com/TheRenegadeCoder)
- Join us on [Discord](https://discord.gg/Jhmtj7Z)
- And, check out the rest of the [list](https://therenegadecoder.com/blog/ways-you-can-help-grow-the-renegade-coder/) which includes links to The Renegade Coder [YouTube channel](https://www.youtube.com/channel/UCpyoVwOqYRlSAEUPEn7P9hw) and [Twitter account](https://twitter.com/RenegadeCoder94)

Thanks for your help!

**Pull request merged**
