### PR TITLE
Added Quick Sort in Haskell

### LINKED ISSUE #813: Add Quick Sort in Haskell

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #813 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by auroq** [comment]
Just trying to give C a run for its money. ;)

**Comment by jrg94** [comment]
Haha that's going to be tough. Haskell seems to be quite a bit more expressive. If you manage to implement some form of Game of Life though, I'm sure you'll overtake it.

**Comment by auroq** [comment]
Have you noticed my branch for game of life in haskell? I believe it's working, but I'm not certain because I'm still working on the UI. I haven't done any GUI in haskell beyond basic vector graphics.

https://github.com/TheRenegadeCoder/sample-programs/blob/haskell-gol/archive/h/haskell/game-of-life.hs

**Comment by jrg94** [comment]
If it becomes too cumbersome, you can opt for a CLI solution instead. We did that for C because, well, it's C.  In fact, the Python GUI barely works beyond small grids. Apparently, it's more efficient to use a canvas, but I'm too lazy to rewrite the solution. We did have a partially working rewrite, but the author never finished it (#254).

**Pull request merged**
