### PR TITLE
Added Square Root in C

### PR DESCRIPTION
**Pull request by hpnightowl**

### CODE REVIEW

**Comment by hpnightowl** [comment]
Ok I will Document it and push it

**Comment by hpnightowl** [comment]
@jrg94 is it good?

**Comment by jrg94** [comment]
Not quite! We would need a Square Root document which outlines exactly what every language would need to implement. See [projects](https://sample-programs.therenegadecoder.com/projects/) for examples.

**Comment by hpnightowl** [comment]
oh! Ok you need the documentation so that we can implement it in every language got it ! i'll try my best

**Comment by jrg94** [comment]
Let me know if you ever get around to this. Going to close for now.

**Pull request closed without merging**
