### PR TITLE
Added Job Sequencing with Deadline in Kotlin

### PR DESCRIPTION
**Pull request by smallblack9**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #your-issue-number-here
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [x] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

## Other Notes

- Hope you don't mind that I renamed some other source code files of Kotlin to match the name convention I used in 'testinfo.yml'.

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by jrg94** [comment]
I really appreciate you taking the time to add testing and clean up our Kotlin situation. 👍 This is awesome.

**Review by jrg94 — CHANGES_REQUESTED** [review]
Awesome! So it looks like a lot of the existing code is failing testing: https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/188685659

**Comment by jrg94** [comment]
Let me know if you want help tackling any of these. I think I can help.

**Comment by smallblack9** [comment]
@jrg94 
Yes, many failures, some of them actually only due to the output messages of the invalid input weren't as same as what are expected. 
As I renamed the files, so I'm not sure if it's good to do it in the same PR.
Would you like me to fix those existing Kotlin codes which are failing in my current PR or create another branch and PR for this?

**Comment by jrg94** [comment]
That's totally up to you. If you want, you can submit a pull request with all the files renamed. Then, you could add another to incorporate this new script. This pull request can be for testing.

**Comment by smallblack9** [comment]
Hi @jrg94 
To make the PR clean, I just removed the testinfo.yml from my current PR.
Then I created another issue #2190 and working on it. Would it be ok for you? Would you mind to assign the #2190  to me?

**Comment by jrg94** [comment]
We are having an issue with a separate Docker image. I'm going to merge this for now.

**Pull request merged**
