### PR TITLE
File IO in Rust

### PR DESCRIPTION
**Pull request by Noah11012**
I hope I'm not overwhelming anybody with this many pull requests in a relatively short amount of time.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [ ] I fixed #your-issue-number-here

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
Of course not! The more the merrier 😄

**Comment by Noah11012** [comment]
Thanks. If someone wants to test it, you can use the [Rust Playground](https://play.rust-lang.org/)

**Comment by jrg94** [comment]
Oh, you're right! It does run. However, I get some odd warnings:

```
   Compiling playground v0.0.1 (file:///playground)
warning: unused `std::result::Result` which must be used
 --> src/main.rs:6:6
  |
6 |      out.write(b"A line of text written to this file in Rust!\n");
  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_must_use)] on by default
  = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` which must be used
 --> src/main.rs:7:5
  |
7 |     out.write(b"Another line also written by a Rust program!\n");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` which must be used
 --> src/main.rs:8:6
  |
8 |      out.flush();
  |      ^^^^^^^^^^^^
  |
  = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` which must be used
  --> src/main.rs:14:5
   |
14 |     in_file.read_to_string(&mut line);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` which must be used
  --> src/main.rs:19:5
   |
19 |     write_file();
   |     ^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` which must be used
  --> src/main.rs:20:5
   |
20 |     read_file();
   |     ^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled

    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `target/debug/playground`
```

**Comment by Noah11012** [comment]
It's complaining that we're ignoring the return values from these methods. I kept it simple so I didn't do anything with the return values. If you don't like the warnings I can correct them.

**Comment by jrg94** [comment]
I don't really have a preference. I'll let someone else in @TheRenegadeCoder/core look it over.

**Comment by chrboe** [comment]
So I don't know a ton about Rust, but what I do know is that it likes to be very explicit about everything (see `mut` for instance). It's the same here: apparently `write` returns the error value along with the result, and according to Rust, this needs to be checked.

I don't think we should "trick" the compiler into accepting that we're not checking the error, and we definitely shouldn't ignore the warnings. I know the code looks kind of bloated with all the error checks in there, but hey, that's just what Rust is all about (enforcing safety at compile time etc), so why not embrace it.

I would suggest something like the following (specifically, the `match` idiom):

```
let mut s = String::new();
match file.read_to_string(&mut s) {
    Err(why) => panic!("couldn't read {}: {}", display,
                                               why.description()),
    Ok(_) => print!("{} contains:\n{}", display, s),
}
```

**Comment by Noah11012** [comment]
Hopefully it won't be too difficult to explain the code in the article.

**Pull request merged**
