### PR TITLE
Added Even Odd in P4

### LINKED ISSUE #2125: Add Even Odd in P4
See requirements: [https://sample-programs.therenegadecoder.com/projects/quick-sort/](https://sample-programs.therenegadecoder.com/projects/quick-sort/)

Add snippet here: [https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/p4](https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/p4)

P4 Documentation [https://p4.org/code/](https://p4.org/code/)`

### PR DESCRIPTION
**Pull request by ecwolf**
- [x] I fixed #2125 

    This is a P4 Even Odd code:

    We defined a new packet header "operation", with.
                            
    number = the 7 bits of the number
    v      = bit 0 of the number will be used to define if it is even or odd
    flag   = will be 0 if even, or 1 if odd

    Let us assume that the operation header is carried over Ethernet and uses
    the Ethertype 0x123 to indicate the presence of the header.

    When a packet arrives to the switch it is validated the header operation.
    Then it is verified the last bit of the number. Is odd if its last digit 
    is 1; it is even if its last digit is 0. The result will be set in flag.

### CODE REVIEW

**Comment by ecwolf** [comment]
It was added a commit "Adding Roman Numeral Conversion in Bash" by mistake

**Comment by jrg94** [comment]
It looks like that file is still there.

**Comment by ecwolf** [comment]
@jrg94 now it is correct. Finally removed the wrong files.

**Review by jrg94 — APPROVED** [review]
Perfect!

**Pull request merged**
