### PR TITLE
Adding 2 Scripts in Python

### PR DESCRIPTION
**Pull request by agasheaditya**
1) given an input of integers to a linked list return squared sorted LL
2) return the maximum sum of the weighted rotated array

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [x] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by Ragas99205 — APPROVED** [review]

**Review by Ragas99205 — APPROVED** [review]

**Review by agasheaditya — COMMENTED** [review]
review has done

**Review by jrg94 — CHANGES_REQUESTED** [review]
Great inclusions, but neither of them are currently supported. Would you be interested in helping us document them?

**Comment by agasheaditya** [comment]
> Great inclusions, but neither of them are currently supported. Would you be interested in helping us document them?

yes sure @jrg94 I'll do that

**Comment by jrg94** [comment]
Sure! Usually, we document things over here: https://github.com/TheRenegadeCoder/sample-programs-website

You can see examples of the things we support here: https://sample-programs.therenegadecoder.com/projects/

Right now, I'm thinking your rotation program is a better fit for our repo than the linked list solution, so let's start there.

**Comment by agasheaditya** [comment]
> Sure! Usually, we document things over here: https://github.com/TheRenegadeCoder/sample-programs-website
> 
> You can see examples of the things we support here: https://sample-programs.therenegadecoder.com/projects/
> 
> Right now, I'm thinking your rotation program is a better fit for our repo than the linked list solution, so let's start there.

okay, sure. So from where should I start?

**Comment by jrg94** [comment]
We have a repo for documentation: https://github.com/TheRenegadeCoder/sample-programs-website

You can try drafting something up using this template: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md

**Comment by agasheaditya** [comment]
@jrg94 Please check my recent pull
If there are any changes you need feel free to contact me again.

**Comment by agasheaditya** [comment]
@jrg94 Please check my recent pull
If there are any changes you need feel free to contact me again.

**Comment by jrg94** [comment]
Right idea! Obviously, we'll have to rework these to get them to match the documentation. I'm going to close this for now. Feel free to reopen with the appropriate changes.

**Comment by agasheaditya** [comment]
> Right idea! Obviously, we'll have to rework these to get them to match the documentation. I'm going to close this for now. Feel free to reopen with the appropriate changes.

Yes sure. will do

**Pull request closed without merging**
