### PR TITLE
Split out test runner and replaced with glotter dependency

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Documentation

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language> Article` format
- [ ] I followed the applicable article template
  - [ ] I added/updated a [language article][4] (i.e. The Python Programming Language)
  - [ ] I added/updated a [code snippet article][3] (i.e. Hello World in Perl)
  - [ ] I added/updated a [project article][5] (i.e. Fizz Buzz in Every Language)

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[3]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/CODE_ARTICLE_TEMPLATE.md
[4]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/LANGUAGE_ARTICLE_TEMPLATE.md
[5]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/docs/templates/PROJECT_ARTICLE_TEMPLATE.md

### CODE REVIEW

**Comment by auroq** [comment]
@jrg94 I think I finally got everything working now.
Just doing some last minute checks. On first glance, the number of tests doesn't match up between here and master, but there's a number of reasons why that could be.

I'll investigate it a little more before marking this ready for review.

**Comment by jrg94** [comment]
This is really exciting! 👍

**Comment by auroq** [comment]
Ya, this has been a lot of work, but I think I'm happy with the outcome. I would still like to find a better way to do the sorting tests, but that's out of scope for this I think.

After this is merged, I'm going to see if I can get some more languages or projects setup for testing to try to keep up with all these hacktoberfest pull requests.

**Comment by jrg94** [comment]
Let me know when you think this is good to go, and I'll merge it! Also, I appreciate the help with the pull requests. They've been a huge pain to review, but I'm excited about it.

**Comment by auroq** [comment]
Ya, I've been out of town for most of October, but I'm hoping to have some time to help out more the rest of this month.

**Comment by jrg94** [comment]
No sweat! I appreciate whatever help you can provide.

**Comment by auroq** [comment]
@jrg94, The time has come. It's all ready!

**Comment by auroq** [comment]
This is an issue with docker hub. See here: https://github.com/TheRenegadeCoder/sample-programs/pull/1630#issuecomment-542326167

**Pull request merged**
