### PR TITLE
Added Merge Sort in Perl

### LINKED ISSUE #1502: Add Merge Sort in Perl
See requirements: https://sample-programs.therenegadecoder.com/projects/merge-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/perl

### PR DESCRIPTION
**Pull request by Ayush7-BIT**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below
Added code for MergeSort in Perl...

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1502 

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [x] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [x] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Same sort of issues as some of your other pull requests. The code has to go in a specific folder.

**Comment by Ayush7-BIT** [comment]
@jrg94 Sir I updated that, kindly see and tell..

**Comment by jrg94** [comment]
When it's finished testing, you can take a peek at the results.

**Comment by Ayush7-BIT** [comment]
Added .py extension, modified variable names and followed PEP8 Guidelines..

**Comment by Ayush7-BIT** [comment]
@jrg94 Ok sir..

**Pull request closed without merging**
