### PR TITLE
Added Hello World in clojure

### LINKED ISSUE #728: Add Hello World in Clojure
See: https://github.com/clojure/clojure

Example:

```clojure
(println "Hello, World!")
```

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #728 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
Actually, I tried testing this a couple times, and I don't see it outputting anything. Any advice?

**Comment by auroq** [comment]
I am not super familiar with Clojure. I was having trouble figuring out how to run it from CLI. I used a few online interpreters. Some output it, some required me to call the function. If you can tell me how you're running it, maybe I can help.

**Comment by jrg94** [comment]
I tried running it in Jdoodle, and it's not printing. I can't find like any documentation on Hello World in Clojure either hahaha

**Comment by auroq** [comment]
I added a call to main so that it works on jdoodle. It seems that clojure isn't commonly written as a single file script. All the hello world examples I find tell me to just generate it using leiningen. Basically, you can only run locally using a full project with a project.clj or by using the repl.

Long story short, I think it makes sense to just add the call to main here so that it can be copy pasted to jdoodle and other online compilers.

**Comment by jrg94** [comment]
Sounds good! I didn't dig into it too much. Worse comes to worse, we get a clojure expert to show up and tear into the implementation. 😆

**Pull request merged**
