### PR TITLE
Added Ruby to Testing Framework

### LINKED ISSUE #1021: Add Ruby to Testing Framework
Create a testinfo.yml file.

### PR DESCRIPTION
**Pull request by jrg94**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [ ] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #1021 

## Notes

Now, I'm just toying around with incorporating new languages. I'm not sure what all the fields in the yml do (namely tag), but I figured I'd open this up for suggestions.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
I'm not sure if it worked or not, but I think the test count went up (from 49 -> 50). All ruby has to offer is baklava at the moment.

**Comment by jrg94** [comment]
How does the command line work in the yml if we have a language that's compiled (i.e. Java/C) which requires a couple lines of code to run (i.e. javac/java).

**Comment by jrg94** [comment]
Looks like testing works! 😄 I don't have time to patch up this ruby bubble sort implementation at the moment. I'll come back to it later.

**Comment by jrg94** [comment]
Pretty cool stuff @auroq! Ruby is up and running. I'll leave this here for your review (and explanation 👍).

**Comment by auroq** [comment]
I finished up the bubble sort in ruby and added it to the readme.
As far as multi-command runs, I have some ideas. I'll probably tackle that after I get tests for all the projects.

**Comment by jrg94** [comment]
Awesome! Thanks again for the help.

**Pull request merged**
