### PR TITLE
Added Pigpen Cipher in Python

### PR DESCRIPTION
**Pull request by JaiunL**
I have no idea if I can add this program here but this is a fairly simple pigpen cipher encoder that I made some time ago. Hope this helps!

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [O] I created/updated the language README
  - [O] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

Sorry if I did something wrong. My first time contributing to a public project.

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is a cool idea! Any chance we could get this documented?

**Comment by JaiunL** [comment]
Sorry but, documented as in? I dont quite follow.

**Comment by jrg94** [comment]
We have a list of projects here: https://sample-programs.therenegadecoder.com/projects/

Basically, we won't accept a program unless it's in this list. In other words, you'd need to document that program to get it included.

**Comment by JaiunL** [comment]
Oh, okay. Thanks. Ill have it documented asap

**Pull request closed without merging**
