### PR TITLE
Added Reverse a String in MATLAB

### LINKED ISSUE #1460: Add Reverse A String in Matlab
See requirements: https://sample-programs.therenegadecoder.com/projects/reverse-a-string/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/m/matlab

### PR DESCRIPTION
**Pull request by iwishiwasaneagle**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [x] I fixed #1460

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This looks good, but we generally expect programs to be executable (i.e. accept a string off the command line).

**Comment by iwishiwasaneagle** [comment]
> This looks good, but we generally expect programs to be executable (i.e. accept a string off the command line).

Can you expand on this please? Looking at the other MATLAB samples it seems that they're almost all functions like this.

**Comment by jrg94** [comment]
Yeah, the MATLAB examples aren't great. Ideally, these should be executable programs. Perhaps MATLAB doesn't fit the typical requirements for this repo. I'll go ahead and merge this for now, and then we'll try to figure out the best path forward at a later time.

**Review by jrg94 — APPROVED** [review]
👍

**Pull request merged**
