### PR TITLE
Added DFS in C++

### LINKED ISSUE #2559: Add Depth First Search in c-plus-plus
To request a new code snippet, please fill out the following:

Project name: ADD DFS code in c++
Project link: https://sampleprograms.io/projects/DFS
Language: C++

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

### PR DESCRIPTION
**Pull request by AjayMaheshwari23**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #2559 
- [x] I named the pull request using `Add {DFS} in {C++}` format

### CODE REVIEW

**Comment by AjayMaheshwari23** [comment]
@jrg94  Can you please tell where it is failing ? and what can i change

**Comment by jrg94** [comment]
It looks like the nodes are hardcoded. The program should run as described here: https://sampleprograms.io/projects/depth-first-search/

**Comment by AjayMaheshwari23** [comment]
Okay I am fixing it

**Comment by AjayMaheshwari23** [comment]
Yes now it passed all the checks . Anything else i need to change or it can be merged now  ?

**Review by jrg94 — APPROVED** [review]
Looks great! Nice work.

**Comment by AjayMaheshwari23** [comment]
Can you please give it hactoberfest-accepted label so that it will be counted towards hactoberfest

**Comment by jrg94** [comment]
It will automatically get approved in 7 days. I marked the repo as hacktoberfest.

**Comment by AjayMaheshwari23** [comment]
okk

**Pull request merged**
