### PR TITLE
Add Convex Hull in Mathematica

### LINKED ISSUE #2628: Add Convex Hull in Mathematica
To request a new code snippet, please fill out the following:

Project name: Convex Hull
Project link: https://sampleprograms.io/projects/convex-hull
Language: Mathematica

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

### PR DESCRIPTION
**Pull request by heksterb**
## I Am Adding a New Code Snippet in an Existing Language

- [X] I fixed #2628
- [X] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
  
  
## Other Notes

Please see my description in the Issue as to the structure of the code and why the tests can only be run manually; any such tests required by the project are included as part of the Pull Request and were verified by me (the author).

Note that this PR is a result of exporting the Mathematica Notebook as text, which drastically reduces its readability: within the Mathematica environment itself the Notebook looks much better, showing both input and output, elegantly formatted.  If you (the Web site maintainers) like, I can provide the Notebook contents as exported HTML (with or without MathML), and the original Notebooks themselves— just let me know.

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks great! In general, we expect the program to run from the command line with command line inputs. We haven't tried that with Mathematica in the repo yet, so let us know if that's not an option. It's currently not tested anyway, so it's not a big deal.

**Comment by jrg94** [comment]
I think since you've added so many of these, and they look generally pretty good... I'm going to merge them. Then, we can talk about formatting them for testing, which would include finding a good Docker image for Mathematica.

**Comment by heksterb** [comment]
Thanks @jrg94 .  With all of these fragments, I generally tried to split them between the actual solution in pure Mathematica style, and a `main` function on top in command-line style that accepts string arguments.  My guess is (I've never tried it) that it should be possible to call those `main` functions through the `wolframscript` tool.

The real challenge is deploying this commercial product in a Docker environment.  A quick search shows that this _may_ be [https://mathematica.stackexchange.com/a/238847/61814](a solved problem) (including the licensing).  I'll try to find time this weekend to look at it.

**Comment by jrg94** [comment]
Awesome! In the meantime, I'm going to slowly work through merging these. This is a process we have to work through with every language, so I don't mind if they're not "perfect" for now.

**Comment by heksterb** [comment]
@jrg94 Just an update on where I stand with all this.  BLUF: in theory, we might be able to get automated tests of Mathematica code to work, but it will take a fair amount of work, changes in Glotter, and possibly cooperation from Wolfram.  So the question is how hard you're willing/wanting to push this to make it so.

There is an [official Mathematica image from Wolfram in Docker Hub](https://hub.docker.com/r/wolframresearch/wolframengine), and it looks like this should work in principle.  However there are a few hurdles that need to be crossed for this all to work in practice:

* licensing:  As I mentioned, Mathematica is a commercial product.  However, the command-line version (called Wolfram Engine) can run with a free 'node-locked' license that is issued against a Wolfram account.  I'm using one activated against my personal account and associated with my personal machine, but that approach probably wouldn't work in GitHub Actions (or whatever other environment you're using) because of the node locking.  There is a possibility we persuade the folks at Wolfram to grant a more flexible license for this open-source project.
* container: needs a couple of tweaks:
  * the license activation process produces a `mathpass` file that needs to be Docker volume'd into the container; so that would require a change in Glotter and `testinfo.yml` to support
  * needs network access for the license validation to work; again, requiring a change in Glotter to support
  * the Mathematica executable seems to need to run as UID 999, which unfortunately means that the temporary directory (owned by whatever user is running Glotter) containing the source code that is volume'd in to the container is inaccessible because of file system permissions.  The simplest solution I see is to open permissions on that temporary directory, which solves the permission problem but clearly isn't the 'right' thing to do.
* glotter: on my Ubuntu 22.04, this needs the following tweaks to run:
  * `markupsafe==2.0.1` (to avoid a "ImportError: cannot import name 'soft_unicode' from 'markupsafe'" error)
  * a more recent `pytest` (to avoid a "pluggy.manager.PluginValidationError: unknown hook 'pytest_collection_modify_items'" error)

**Comment by jrg94** [comment]
Thanks for the heads up! This is very informative. I'm perfectly comfortable with where the repo is at right now, so there's no need to actually get these tested. It would be nice, but there are several hurdles as you mentioned.

Also, glotter hasn't been modified in some time (and we're aware of some of the bugs). It was most recently maintained by @auroq, but I suspect he's moved on from both projects. If so, we could potentially fork glotter to keep it maintained. There are definitely some changes we've been looking to make. For instance, it would be nice to create test configuration files (e.g., in YAML), rather than writing everything in Python. 

Overall, I appreciate the effort you put into this! I think the next bit of effort will have to go into glotter before we continue are efforts with Mathematica.

**Pull request merged**
