### PR TITLE
Run suite

### PR DESCRIPTION
**Pull request by auroq**
Quite a few changes in here. Basically I abstracted out some of the stuff I created for tests. Then I created a CLI entrypoint to the whole thing, so you can either run a source or verify it with a test. Then I wrapped everything in a bash script to make it easier to run.

For usage try the following:
`./samplerunner.sh --help`
`./samplerunner.sh run --help`
`./samplerunner.sh test --help`

To run all tests do `./samplerunner.sh test` or just use `./test.sh` that existed already.
To run all programs (without test verification) do `./samplerunner.sh`

As far as projects that need parameters, the runner will intelligently prompt when it requires input.

### CODE REVIEW

**Comment by auroq** [comment]
FYI, I don't know if this will fix the build, but I think it is a good step to doing so.
I can use this new runner to have an entrypoint for just downloading all the required docker images.
We can download 3 at a time with output. That way the build doesn't complain that it's not getting output, and it will run faster overall because we can get 3 images simultaneously.

(3 specifically, because that's the default maximum simultaneous downloads of the docker engine.)

**Comment by jrg94** [comment]
That sounds great! If there's a way to perform logging, it should go here:

https://github.com/TheRenegadeCoder/sample-programs/blob/3f4888850f7713ad3d11733a09509c0d5c22538f/.travis.yml#L6

That way, we include the downloading and building of images in the install phase and tests are separate.

**Comment by jrg94** [comment]
Just got a chance to play with your runner. Very, very cool stuff. I like that you can segment testing by project and by language.

**Comment by jrg94** [comment]
So, I'm still having issues running docker locally. Here's the latest error:

```shell
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

e = HTTPError('500 Server Error: Internal Server Error for url: https://192.168.99.100:2376/v1.35/containers/create?name=selection_sort_e7f5b3cf2b1c49d09e2ba7239ba7bfdf')

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid volume specification: 'C:\Users\jerem\AppData\Local\Temp\tmp7eg9jgmk:/src:rw'")

..\..\..\..\AppData\Local\Programs\Python\Python37-32\lib\site-packages\docker\errors.py:31: APIError
======================================== 72 failed, 14 error in 45.95 seconds =========================================
```

I think this error has to do with how paths are handled on Linux vs. Windows. My only argument for that is the following link: https://github.com/awslabs/aws-sam-cli/issues/408

**Comment by jrg94** [comment]
Nevermind. Apparently this is an issue with Docker Toolkit. Unfortunately, I can't install Docker for Windows because I don't have the fancy version of Windows (Pro/Enterprise) on either of my systems. I think I'm going to virtual box this up.

**Comment by jrg94** [comment]
Actually, still a path issue I believe. Backslashes are the path separator on Windows by escape characters basically everywhere else. Ugh.

**Comment by auroq** [comment]
Hmm. I was under the impression that python would still handle that because they're packages. I'm installing docker on my surface right now, so I can debug for myself.

**Comment by jrg94** [comment]
Thanks! I may just be doing something wrong. I have tried it on both my desktop and my surface, so who knows. haha

**Comment by jrg94** [comment]
Good news! I have added which languages have tests to the wiki (dynamically, of course). 🔥

**Comment by auroq** [comment]
Hmmm, I just ran it on my surface. No trouble with the exception of a few failures due to line endings. I wonder if it is a difference between docker toolbox and docker desktop.

**Comment by jrg94** [comment]
You’re probably right! That was the vibe I was getting from the discussion in the link I shared. Oh well. I’m planning to setup Linux as a workaround for the time being. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Also, thanks for investigating! I appreciate the help. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
I think if we remove the testinfo file for C# and resolve whatever conflicts there are on master, this can be merged.

**Pull request merged**
