### PR TITLE
Added Convex Hull in C#

### PR DESCRIPTION
**Pull request by SirePi**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [ ] I fixed #your-issue-number-here
- [X] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

  
## Other Notes

I just noticed that the relevant issue #1281 was closed 4 days ago but I didn't see the snippet.. worst case, just throw this away 😄 

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by jrg94** [comment]
No sweat! I had actually done some issue cleanup recently, so I got rid of a ton from last year that hadn't been accepted. This is totally cool, and we appreciate it.

**Review by jrg94 — CHANGES_REQUESTED** [review]
So, I just realized that our Convex Hull solution isn't well documented. Any chance you'd like to help us fix it up? See: https://sample-programs.therenegadecoder.com/projects/convex-hull/

Basically, we expect there to be a table in testing which we can convert into tests for this repo.

**Comment by jrg94** [comment]
Yeah, splitting these apart would be awesome.

Here's the file you'd need to edit to add testing: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/projects/convex-hull/index.md

**Comment by SirePi** [comment]
Will redo as requested

**Pull request closed without merging**
