### PR TITLE
Hello world in NODE.JS

### PR DESCRIPTION
**Pull request by VatsalNarwal**
I made a HELLO WORLD website application in NODE.JS

### CODE REVIEW

**Review by jrg94 — COMMENTED** [review]
Really cool stuff, but we actually treat node and js as the same thing in this repo. If you think we need to distinguish them, we can chat about it.

**Comment by VatsalNarwal** [comment]
Okay, I agree. Node.JS is actually a JS library but JS is not a server-side scripting language however Node.JS is a dynamic server-side scripting language. Node.JS comes with a number of plugins like Express, Socket.io etc. however this is not possible with JS.

**Comment by jrg94** [comment]
True! That said, in a repo that tries to create code snippets that are functionally identical to each other (https://sample-programs.therenegadecoder.com/projects/), would two programs in these languages largely look the same?

**Comment by VatsalNarwal** [comment]
okk

**Pull request closed without merging**
