### PR TITLE
Damaru in C

### PR DESCRIPTION
**Pull request by sagarnikam123**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [x] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [ ] I fixed #your-issue-number-here

## Notes
Please add label `Hacktoberfest`

### CODE REVIEW

**Comment by jrg94** [comment]
Hey @sagarnikam123! Just checking in. 👍

**Comment by Noah11012** [comment]
I've seen your new changes @sagarnikam123. What we mean by explaining the sample program is to write in a file describing the problem in a formal fashion. This includes the name of the problem, what the problem is and what is the goal, the restrictions, etc.

**Comment by jrg94** [comment]
I'd love to include this program 👍 Damaru is similar to Baklava correct?

**Comment by sagarnikam123** [comment]
> I'd love to include this program  Damaru is similar to Baklava correct?

@jrg94, Yes, Damaru is similar to Baklava.

**Comment by jrg94** [comment]
If we're going to merge this, we need a complete description of the program added to the Docs folder. Otherwise, we'll have to close this out.

**Comment by jrg94** [comment]
Closing this for now.

**Pull request closed without merging**
