### PR TITLE
Added Remove All Whitespace Testing and Solution in C

### PR DESCRIPTION
**Pull request by barhouum7**
Big thanks to [The Renegade Coder][renegade-coder]!
  
## I Am Adding a New Code Snippet in a New Language

- [x] I fixed [#2290 ](https://github.com/TheRenegadeCoder/sample-programs/issues/2290)
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
- [x] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])
  

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by barhouum7** [comment]
I added project documentation for this sample program in this PR [#373](https://github.com/TheRenegadeCoder/sample-programs-website/pull/373)

**Comment by jrg94** [comment]
Awesome! Documentation is merged. Now, we need to add testing, so we can make sure your program conforms to the spec.

**Comment by barhouum7** [comment]
> Awesome! Documentation is merged. Now, we need to add testing, so we can make sure your program conforms to the spec.

Okay, that's good! If don't mind, I need you add the hacktoberfest-accepted label??

**Comment by jrg94** [comment]
I'll just accept this for now, and we can edit it later.

**Review by jrg94 — APPROVED** [review]
Approved for the purpose of satisfying Hacktoberfest guidelines. Currently, pending testing.

**Comment by barhouum7** [comment]
> I'll just accept this for now, and we can edit it later.

Thanks, I am looking forward

**Comment by jrg94** [comment]
Any chance you could help us put together testing for this?

**Comment by barhouum7** [comment]
> Any chance you could help us put together testing for this?

Okay! How can I help you?

**Comment by jrg94** [comment]
Yes! Basically, we need a new file here that recreates the testing table from your documentation: https://github.com/TheRenegadeCoder/sample-programs/tree/master/test/projects

Also, this file needs updated: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.glotter.yml

As well as this one: https://github.com/TheRenegadeCoder/sample-programs/blob/master/runner.py

**Comment by barhouum7** [comment]
> Yes! Basically, we need a new file here that recreates the testing table from your documentation: https://github.com/TheRenegadeCoder/sample-programs/tree/master/test/projects
> 
> Also, this file needs updated: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.glotter.yml
> 
> As well as this one: https://github.com/TheRenegadeCoder/sample-programs/blob/master/runner.py

Okay! I'll work on it

**Review by jrg94 — CHANGES_REQUESTED** [review]
Alright, I fixed a bunch of stuff. I suspect that this will test properly now (but fail). Make sure to check testing when it's finished.

**Comment by barhouum7** [comment]
> Alright, I fixed a bunch of stuff. I suspect that this will test properly now (but fail). Make sure to check testing when it's finished.

It fails again! But I think this file `archive/c/c/testinfo.yml` may cause the fail.

```yml
container:
  image: "gcc"
  tag: "8.3" 
  build: "gcc -o {{ source.name }} {{ source.name }}{{ source.extension }}"
  cmd: "./{{ source.name }}"
```
The cmd value may should be `"{{ source.name }}"` instead of `"./{{ source.name }}"`
What do you think?

**Comment by jrg94** [comment]
The testinfo file is file. The issue is actually with the Python test file that was added, I believe.

**Comment by barhouum7** [comment]
> The testinfo file is fine. The issue is actually with the Python test file that was added, I believe.
> 
> Actually, it looks like this is the issue:
> 
> ```
> remove-all-whitespace.c:15:10: fatal error: conio.h: No such file or directory
> E                #include <conio.h>
> E                         ^~~~~~~~~
> E               compilation terminated.
> ```

I can remove this library since it caused this problem..?

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks like tests are running! Now it's just a matter of fixing the bugs.

**Pull request closed without merging**
