### PR TITLE
Revert "Revert "Split out test runner and replaced with glotter dependency""

### PR DESCRIPTION
**Pull request by auroq**
Reverts TheRenegadeCoder/sample-programs#1630

Reverting the revert as the problems were caused by docker hub not by the new changes:

https://github.com/TheRenegadeCoder/sample-programs/pull/1630#issuecomment-542326167
https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5da5fc78c7b1c11cd8603721

### CODE REVIEW

**Comment by jrg94** [comment]
I think I realized this and reverted it already. haha my bad.

**Comment by jrg94** [comment]
See #1631

**Comment by jrg94** [comment]
Nice call on the status issue!

**Comment by jrg94** [comment]
So weird how this timed up with the new change.

**Comment by auroq** [comment]
Right. What are the chances?

**Pull request closed without merging**
