### PR TITLE
Modified Test File in Clojure

### LINKED ISSUE #2191: Clojure Tests Are Breaking
I thought maybe this was a short term issue, but I inspected DockerHub. It looks like they uploaded new images 3 hours ago, and now our tests are breaking. 🔥

### PR DESCRIPTION
**Pull request by jrg94**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution

## I Am Modifying an Existing Code Snippet or Existing Tests

- [x] I fixed #2191 
- [x] I have read about modifying existing code snippets or tests in the [contributing documentation][contributing-modifications]
- [x] I have explained why this modification is _necessary_ either in the issue linked above or in the notes below
- [x] I named the pull request using `Modify {PROJECT} {tests} in {LANGUAGE}` format

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Comment by jrg94** [comment]
Alright, this should fix our Clojure issue. Clearly, the original image was pulling latest which caused this issue.

**Comment by auroq** [comment]
Generally, I'm all for tagging a specific version, but I wonder if we should try to solve the original issue as well so we don't fall behind. Coincidentally, I've been looking at adding testing for lisp today. I can take a look at this next.

**Comment by jrg94** [comment]
Oh for sure! I noticed our trend in some of the other languages was to use tagged versions. I don't mind updating the versions, but I think that should be opt-in. In other words, we should manually update test versions rather than depend on "latest". Otherwise, we end up with these situations where branches start failing at random. Of course, the risk of falling behind is definitely there.

**Comment by auroq** [comment]
Ya, I agree completely. I guess the way to not fall behind is that anyone who wants to contribute to an existing language and wants/needs a new version will be responsible for updating.

**Pull request merged**
