### PR TITLE
Binary Search in C

### LINKED ISSUE #3294: Add Binary Search in C
To request a new code snippet, please fill out the following:

Project name: Binary Search
Project link: https://sampleprograms.io/projects/binary-search
Language: C

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

### PR DESCRIPTION
**Pull request by 2Clutch**
## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #3294
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format

### CODE REVIEW

**Comment by 2Clutch** [comment]
Am I supposed to do anything to fix the testing error?

**Comment by rzuckerm** [comment]
@2Clutch The C file is empty.

**Review by rzuckerm — CHANGES_REQUESTED** [review]
Needs more code 😄

**Review by rzuckerm — CHANGES_REQUESTED** [review]
Input needs to come from command-line arguments. Please refer to the [project documentation](https://sampleprograms.io/projects/binary-search/) for details

**Review by rzuckerm — CHANGES_REQUESTED** [review]
The arguments are suppose to come from the command-line arguments, not stdin. Also, please read the [project documentation](https://sampleprograms.io/projects/binary-search/). It clears states the input and output requirements.

**Comment by 2Clutch** [comment]
I'm taking input from the command line. Unless I'm supposed to also follow the copy as-is? (i.e. `Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")`)

**Comment by rzuckerm** [comment]
> My latest push processed input from the command line. Unless I'm supposed to also follow the copy as-is? (i.e. `Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")`)

Yes, those are the requirements. The tests will looks for that specific string for invalid inputs. Until the tests pass, I cannot merge this PR

**Review by rzuckerm — CHANGES_REQUESTED** [review]
There is still one test that is failing:
```
FAILED test/generated/test_binary_search.py::test_binary_search_invalid[c/binary-search.c-missing input: list] - assert 'false' == 'Usage: pleas...o find ("11")'
  - Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")
  + false
```
The size of input array must be at least 1.

**Comment by 2Clutch** [comment]
Will look at this again sometime tomorrow or sometime during the week because I'm not sure what I'm doing wrong. 

It would be great if the error logs were a bit more descriptive. In going through, every tests than ran successfully passed, but an issue seems to arise at the clean up phase?

Screenshot 2024-10-27 at 1 29 17 PM

Prior to that, there was a set of 1K tests that went through fine and there was no issue during the clean up stage.

If you have any hints or advice, I'd appreciate it.

**Comment by rzuckerm** [comment]
The problem is that the empty input case is not being handled. This is not an issue with the cleanup. It's just that the final failing result is not returned until all of the tests are done. The tests are broken up into a total of 6 batches to keep from filling up the server with docker images. The `C` code is tested in the first batch, and the actual failure happens [here](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11543406385/job/32127757920#step:7:2928). I think all you need to do is add something like this after the call to `parseInput`:
```c
if (size == 0) {
    printf("Usage: please provide a list of sorted integers (\"1, 4, 5, 11, 12\") and the integer to find (\"11\")");
   return 1;
}
```
Just a suggestion, but I'd probably put the error message in a common function so that it is not repeated so much.

**Comment by 2Clutch** [comment]
> The problem is that the empty input case is not being handled. This is not an issue with the cleanup. It's just that the final failing result is not returned until all of the tests are done. The tests are broken up into a total of 6 batches to keep from filling up the server with docker images. The `C` code is tested in the first batch, and the actual failure happens [here](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11543406385/job/32127757920#step:7:2928). I think all you need to do is add something like this after the call to `parseInput`:
> 
> ```c
> if (size == 0) {
>     printf("Usage: please provide a list of sorted integers (\"1, 4, 5, 11, 12\") and the integer to find (\"11\")");
>    return 1;
> }
> ```
> 
> Just a suggestion, but I'd probably put the error message in a common function so that it is not repeated so much.

I'm aware. Will make one final push that provides a clean structure once all of all the tests pass.

**Review by rzuckerm — APPROVED** [review]
Thanks, @2Clutch , for your persistence and patience. I currently have an issue logged to address the lengthy and confusing test workflow. I'll see what @jrg94 thinks about this before making any changes

**Comment by 2Clutch** [comment]
I had one more push with a better code structure that got rid of the repeated code. Can I still make that push?

**Comment by rzuckerm** [comment]
> I had one more push with a better code structure that got rid of the repeated code. Can I still make that push?

No, this PR has been merged. If you wish to make an improvement, you'll need to log another issue called "Modify Binary Search in C" and do another PR with the same title.

**Pull request merged**
