### PR TITLE
Added Singleton Pattern in Java

### PR DESCRIPTION
**Pull request by MarkusSYT**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [X] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [X] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Great addition! Any chance we could get it documented first? https://sample-programs.therenegadecoder.com/projects/

**Comment by MarkusSYT** [comment]
> Great addition! Any chance we could get it documented first? https://sample-programs.therenegadecoder.com/projects/

How can I add it to the documentation?

**Comment by jrg94** [comment]
Hmmm. Let me think about this. How would we write a program to test this?

**Comment by MarkusSYT** [comment]
Everything you need is in the file you can test it by creating a second object

**Comment by jrg94** [comment]
I understand, but singletons are unique to OOP, right? In a collection of code snippets in as many languages as possible, I think it may be hard to replicate this.

**Comment by MarkusSYT** [comment]
well yeah you're right

**Pull request closed without merging**
