### PR TITLE
Added TCP Server in Python

### PR DESCRIPTION
**Pull request by ThribhuvanGuptaS**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by ThribhuvanGuptaS** [comment]
I have added a TCP server program which can send and receive text messages with a client

**Review by jrg94 — COMMENTED** [review]
Very cool idea! I'm wondering if this is a good fit for the repo. If so, we'd need to get this documented.

**Comment by ThribhuvanGuptaS** [comment]
Sorry but what type of documentation is needed?

**Comment by jrg94** [comment]
Here's a list of our approved projects: https://sample-programs.therenegadecoder.com/projects/

Here's where the documentation needs to go: https://github.com/TheRenegadeCoder/sample-programs-website

And, here's a template to get you started: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md

**Pull request closed without merging**
