### PR TITLE
Added String Length in Python

### PR DESCRIPTION
**Pull request by RishavHimmatramka**
Language- Python

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Is this basically a string length script? That sounds good! Let's get this documented here: https://github.com/TheRenegadeCoder/sample-programs-website

**Comment by RishavHimmatramka** [comment]
Its a string length script but it can count no. of digits as well.
Test-case1:
Input: 126378
Output: The number of digits are 6.

Test-case2:
Input: Hello
Output: The number of digits are 5.

**Comment by RishavHimmatramka** [comment]
Also please add hacktoberfest label to this.

**Comment by jrg94** [comment]
Okay cool! Currently, we don't support this, but we would definitely be interested in supporting it. Any chance you'd like to write us some documentation?

**Comment by RishavHimmatramka** [comment]
Sorry I am new to github. Can you elaborate further? What is doecumentation?

**Comment by jrg94** [comment]
Yeah, no problem! I'd recommend reading through this document first: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md

That said, basically we maintain a list of approved projects here: https://sample-programs.therenegadecoder.com/projects/

If you wanted this code snippet included, you would need to help us get it documented and tested first.

**Pull request closed without merging**
