### PR TITLE
Convex Hull in C

### LINKED ISSUE #627: Add convex hull in C

### PR DESCRIPTION
**Pull request by clarkimusmax**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [X] I named the pull request using `<Sample Program> in <Language>` format
- [X] I created/updated the language README
  - [X] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [X] I added reference link(s) to the README
  - [X] I added solution citations when necessary (see [plagiarism][2])
- [X] I fixed #627

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by Noah11012** [comment]
Can you create an issue for article creation and link to it in the README.md file?

**Comment by clarkimusmax** [comment]
> Can you create an issue for article creation and link to it in the README.md file?

Issue 628, it was already added to README.md.

**Comment by Noah11012** [comment]
Currently, I can't merge this in because of the merge conflicts that it will create. Could you please fix them?

**Comment by clarkimusmax** [comment]
> Currently, I can't merge this in because of the merge conflicts that it will create. Could you please fix them?

I believe I fixed them with that last commit.

**Comment by Noah11012** [comment]
Yup! All fixed.

**Comment by Noah11012** [comment]
I scanned the sample program with clang-tidy and this is the output I got:

```
/home/noah/Desktop/main.c:47:3: warning: 2nd function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
                printf("(%ld, %ld)\n", nexthullpoint->x, nexthullpoint->y);
                ^
/home/noah/Desktop/main.c:20:6: note: Assuming 'argc' is >= 3
        if (argc < 3 || argc % 2 != 1)
            ^
/home/noah/Desktop/main.c:20:6: note: Left side of '||' is false
/home/noah/Desktop/main.c:20:18: note: Assuming the condition is false
        if (argc < 3 || argc % 2 != 1)
                        ^
/home/noah/Desktop/main.c:20:2: note: Taking false branch
        if (argc < 3 || argc % 2 != 1)
        ^
/home/noah/Desktop/main.c:24:11: note: Uninitialized value stored to field 'x'
        points = malloc(sizeof(struct point) * numpoints);
                 ^
/home/noah/Desktop/main.c:25:6: note: Assuming 'points' is non-null
        if (!points) {
            ^
/home/noah/Desktop/main.c:25:2: note: Taking false branch
        if (!points) {
        ^
/home/noah/Desktop/main.c:30:14: note: Assuming 'i' is >= 'numpoints'
        for (i = 0; i < numpoints; i++) {
                    ^
/home/noah/Desktop/main.c:30:2: note: Loop condition is false. Execution continues on line 39
        for (i = 0; i < numpoints; i++) {
        ^
/home/noah/Desktop/main.c:40:2: note: Loop condition is false. Execution continues on line 43
        for (i = 1; i < numpoints; i++)
        ^
/home/noah/Desktop/main.c:47:3: note: 2nd function call argument is an uninitialized value
                printf("(%ld, %ld)\n", nexthullpoint->x, nexthullpoint->y);
                ^
➜  ~/Desktop  
```

**Comment by clarkimusmax** [comment]
> I scanned the sample program with clang-tidy and this is the output I got:
> 
> ```
> /home/noah/Desktop/main.c:47:3: warning: 2nd function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
>                 printf("(%ld, %ld)\n", nexthullpoint->x, nexthullpoint->y);
>                 ^
> /home/noah/Desktop/main.c:20:6: note: Assuming 'argc' is >= 3
>         if (argc < 3 || argc % 2 != 1)
>             ^
> /home/noah/Desktop/main.c:20:6: note: Left side of '||' is false
> /home/noah/Desktop/main.c:20:18: note: Assuming the condition is false
>         if (argc < 3 || argc % 2 != 1)
>                         ^
> /home/noah/Desktop/main.c:20:2: note: Taking false branch
>         if (argc < 3 || argc % 2 != 1)
>         ^
> /home/noah/Desktop/main.c:24:11: note: Uninitialized value stored to field 'x'
>         points = malloc(sizeof(struct point) * numpoints);
>                  ^
> /home/noah/Desktop/main.c:25:6: note: Assuming 'points' is non-null
>         if (!points) {
>             ^
> /home/noah/Desktop/main.c:25:2: note: Taking false branch
>         if (!points) {
>         ^
> /home/noah/Desktop/main.c:30:14: note: Assuming 'i' is >= 'numpoints'
>         for (i = 0; i < numpoints; i++) {
>                     ^
> /home/noah/Desktop/main.c:30:2: note: Loop condition is false. Execution continues on line 39
>         for (i = 0; i < numpoints; i++) {
>         ^
> /home/noah/Desktop/main.c:40:2: note: Loop condition is false. Execution continues on line 43
>         for (i = 1; i < numpoints; i++)
>         ^
> /home/noah/Desktop/main.c:47:3: note: 2nd function call argument is an uninitialized value
>                 printf("(%ld, %ld)\n", nexthullpoint->x, nexthullpoint->y);
>                 ^
> ➜  ~/Desktop  
> ```

Can you share the clang-tidy command you ran so I can look into this a bit more?

I'm not very familiar with the LLVM suite, but after some research, I think the issue may be related to #1 here:  https://clang-analyzer.llvm.org/faq.html.  The `if argc` assures we get at least one point, `getlongorexit` doesn't return if invalid input is detected, and `leftmost = points` before the for loop guarantees that a valid point will get assigned to `nexthullpoint`, therefore making it impossible to have an uninitialized x in the printf.  My guess is that the analyzer failed to follow the x assignment to points[i] all the way down to the nexthullpoint->x deref in the printf.  Send me the command and I'll look into it more.

**Comment by clarkimusmax** [comment]
Ok, I figured this out.  The following assumption clang-tidy made is *always* incorrect:
'/home/vader/Source/hacktoberfest18/temp/sample-programs/archive/c/c/convex-hull.c:37:14: note: Assuming 'i' is >= 'numpoints'
        for (i = 0; i < numpoints; i++) {
                    ^'

**Numpoints must always be 1 or more:**
Argc is minimum of 3:
'if (argc < 3 || argc % 2 != 1)'

Which means numpoints must be at least 1:
'numpoints = (argc - 1) / 2;'

**Pull request merged**
