### PR TITLE
Fibonacci in Java

### PR DESCRIPTION
**Pull request by MariusGarbea**
- [YES] I named the pull request using `<Sample Program> in <Language>` format

### CODE REVIEW

**Comment by jrg94** [comment]
Quick note! We missed a case in this one and C#. What happens if the user enters a string that isn’t a number?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
I think we might want to try to cover that case. Though, I'm not sure there's a pretty way of handling it beyond try/catch. Let's see if anyone in @TheRenegadeCoder/core has a strong opinion.

**Comment by jrg94** [comment]
For now though, we can merge this in. Can you update the README to include this sample program?

**Comment by MariusGarbea** [comment]
Ok, we can change all of them in one PR if we decide we need to handle the exception gracefully

**Comment by jrg94** [comment]
Agreed!

**Pull request merged**
