### PR TITLE
Added Roman Numeral Conversion in Ruby

### LINKED ISSUE #2146: Add Roman Numeral Conversion in Ruby
See requirements: https://sample-programs.therenegadecoder.com/projects/roman-numeral-conversion/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/r/ruby

### PR DESCRIPTION
**Pull request by AllanKlaus**
### Complete the Applicable Sections Below

- [x] I fixed #2146

### Code Snippets

- [x] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added reference link(s) to the README

### Testing

- [x] Run `ruby archive/r/ruby/roman-numeral.rb VALID_ROMAN_NUMBER`

## Notes

I created the code to convert Roman numeral in Ruby. I used the method `tally` that is only available on `ruby 2.7+`. If you use a older version it will break.

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks great! A couple cases are failing, however: https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/188049114

**Comment by AllanKlaus** [comment]
I'm not too familiar with python, how can I run the tests locally to fix it and only push it solved?

**Comment by jrg94** [comment]
I think there's some directions in the contributing doc: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests

Let me know if you need more!

**Review by jrg94 — CHANGES_REQUESTED** [review]
Looks like the error message prints with an extra set of quotes. Also, one of the calculations is wrong. Otherwise, looks good!

**Review by jrg94 — APPROVED** [review]
Awesome! This works great now. Thanks for the help.

**Pull request merged**
