### PR TITLE
Add Convex Hull JavaScript

### LINKED ISSUE #3354: Add Convex Hull in Javascript
To request a new code snippet, please fill out the following:

Project name: Convex Hull
Project link: https://sampleprograms.io/projects/convex-hull
Language: Javascript

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

### PR DESCRIPTION
**Pull request by GriffinAnnshual**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #3354
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-new-language]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-language
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sampleprograms.io/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by rzuckerm — CHANGES_REQUESTED** [review]
Looks like you have several [test failures](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/6461607853/job/17542655429?pr=3441#step:6:5972) to address. One of these is the error message, which should be this:
```
Usage: please provide at least 3 x and y coordinates as separate lists (e.g. "100, 440, 210")
```

**Comment by rzuckerm** [comment]
@GriffinAnnshual I'll give you hint as to a problem with your implementation. You missing a key first step. See [this](https://en.wikipedia.org/wiki/Graham_scan) for details.

**Comment by GriffinAnnshual** [comment]
@rzuckerm Bro where is the mistake is it in the implementation or on the test cases?

**Comment by rzuckerm** [comment]
> @rzuckerm Bro where is the mistake is it in the implementation or on the test cases? Could you please help?

The mistake in the implementation is that the first point is used to calculate the angles. According to [this](https://en.wikipedia.org/wiki/Graham_scan#Pseudocode), the point with the lowest y-coordinate is supposed to be used:

```
find the lowest y-coordinate and leftmost point, called P0
sort points by polar angle with P0, if several points have the same polar angle then only keep the farthest
```

The test case that is failing called called "Sample Input Pentagon" in [this](https://sampleprograms.io/projects/convex-hull/).

**Comment by GriffinAnnshual** [comment]
Okay got it.. will work on it?

**Review by rzuckerm — APPROVED** [review]
Since this is the last day of Hacktoberfest, I went ahead and fixed this sample since it was pretty close to working.

**Pull request merged**
