### PR TITLE
Added Hello World in Lux

### LINKED ISSUE #44: Add Hello World in Lux
Found another open-source functional language: https://github.com/LuxLang/lux

### PR DESCRIPTION
**Pull request by SubhasmitaSw**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #44 
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [x] I created/updated the language README (see [contributing documentation][contributing-readme])
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [x] I added solution citations when necessary (see [plagiarism][contributing-plagiarism])

  

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: ../CONTRIBUTING.md
[sample-programs-project-list]: https://sample-programs.therenegadecoder.com/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/contributing/.github/CONTRIBUTING.md#modifying-existing-code-snippets

### CODE REVIEW

**Review by auroq — CHANGES_REQUESTED** [review]
Always cool to see new languages!

Could you please add testing for this before we merge it? See https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail

Also, I'm not familiar with Lux. Do we need both the `.clj` and the `.lux` file. If so, is there way to generate one from the other? Our testing framework is currently only setup to handle one file per code snippet unless the other files are generated with a build/compile command.

**Comment by Ask-Subhasmita** [comment]
@auroq The .clj file automates the buildup tool for  .lux files to run as this language is quite new and it doesn't have any build tool yet and it uses Leiningen for this purpose hence the the command under  .clj file enables all the required processes for the seamless running of the lux language programs.

**Comment by auroq** [comment]
Hmm... That makes a lot of sense. Is there anyway to join them into one file?

This is the first time we've needed to have more than one file for any code snippet.

We could probably make some changes to the test runner, but I wonder if conceptually, this is more of a "build step"
In which case we could just set build setting in the `testinfo.yml` to something like the following:

```yml
build: |
  echo '(defproject my_project "0.1.0-SNAPSHOT"
  :plugins [[com.github.luxlang/lein-luxc "0.5.0"]]
  :dependencies []
  :lux {:program "main"}
  :source-paths ["source"]
 )' > {{ source.name}}{{ clj }}"
```

@jrg94 thoughts?

**Comment by jrg94** [comment]
Yeah, I'm not sure. I tried looking into this language to have a more informed opinion, but the documentation is pretty light.

**Comment by Ask-Subhasmita** [comment]
Well, if in the readme section we provide instruction along with the code for the setup to run the programs, How would that be?
 
@auroq @jrg94 Can this work?

**Comment by auroq** [comment]
I think putting something about the file in the Readme is a great idea. Definitely should do that. 

However, it sounds as though without the file the program can't run. So we do still need it to make it in with the tests. Could we try the build line I mentioned above?

**Comment by Ask-Subhasmita** [comment]
@auroq Sounds Great ✨

**Comment by Ask-Subhasmita** [comment]
@auroq @jrg94 Hey, I'm occurring some issues while writing the tests as I've never written one before, can I request some guidance from you ?

**Comment by auroq** [comment]
> @auroq @jrg94 Hey, I'm occurring some issues while writing the tests as I've never written one before, can I request some guidance from you ?

Absolutely. What sort of guidance do you need?

**Pull request closed without merging**
