### PR TITLE
Add Longest Common Subsequence in Go

### LINKED ISSUE #998: Add Longest Common Subsequence in Go

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #998 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by auroq** [comment]
Number 1000! :grinning:

**Comment by jrg94** [comment]
I tweeted about it. This is exciting stuff.

**Comment by auroq** [comment]
Very exciting stuff. Btw, I mentioned this project in a blog post at work: https://www.pluralsight.com/tech-blog/temporary-development-environments

**Comment by jrg94** [comment]
Just read it! 😄 Do you have any docker files you could share with the repo? That was something we wanted to do awhile back (#285), but never went through with it (except Opa and Python).

**Comment by auroq** [comment]
I am very experienced with Docker and have actually been thinking about something like that. Rather than having a Dockerfile per file/language that people have to build themselves, I've wondered about implementing a runner (script?) for the project where you select which project you want to run and in which language, and it would use Docker int he backend to run it.

I've also considered doing something for testing purposes. Basically, implementing a set of unit tests for each project that is run against the file in a pull request. It would use Docker in the backend to setup an environment to run the file and then compare the response against the expected.

**Comment by auroq** [comment]
If you're interested, I could start work on one or both of those.

**Comment by jrg94** [comment]
I'd love to have some way to have automated testing in whatever form that takes. Both are great ideas! Feel free to start either of them. Let me know if I can help in any way.

**Pull request merged**
