### PR TITLE
Haskell Testing

### PR DESCRIPTION
**Pull request by jrg94**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [ ] I named the pull request using `<Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [ ] I fixed #your-issue-number-here

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
I'm really enjoying your testing framework @auroq. It's alarmingly simply to put together the testinfo.yml and watch the tests run. Very easy to see why the tests fail and how to fix them. Looks like all of these errors in Haskell are just output formatting.

**Comment by auroq** [comment]
This one should be done as well, but I think the build may fail for the same reason as C#. (This includes the C# changes)

**Comment by jrg94** [comment]
I'll look into C# as well. See if we can do anything on the Travis end.

**Comment by jrg94** [comment]
Pulled the C# testinfo file out of this build. If successful, will merge.

**Pull request merged**
