### PR TITLE
added Python made JPG to PNG converter

### PR DESCRIPTION
**Pull request by Attupatil**
Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [x] I named the pull request using `Added Python made JPG to PNG conberter in python` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `added Python made JPG to PNG converter` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
Very cool! Any chance we can get this documented? https://sample-programs.therenegadecoder.com/projects/

**Comment by Attupatil** [comment]
Hello @jrg94 I didnt understand what do you mean by documented.
shall I make a documentation for the project or is my project rejected? 
or you mean to say I shall make projects mentioned in https://sample-programs.therenegadecoder.com/projects/

**Comment by Attupatil** [comment]
I can Make fibbo series in c

**Comment by jrg94** [comment]
It's tough to say! We're currently trying to scope down the repo a bit, so if you wanted to add this code, you'd need to add documentation and testing. I'm not sure how you would actually test this kind of program.

**Pull request closed without merging**
