### PR TITLE
Even/Odd in Haskell

### LINKED ISSUE #742: Add Even Odd in Haskell

### PR DESCRIPTION
**Pull request by auroq**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language][1] repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [x] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])
- [x] I fixed #742 

## Notes

Feel free to put whatever you want here.

[1]: https://therenegadecoder.com/code/sample-programs-in-every-language/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md#plagiarism

### CODE REVIEW

**Comment by jrg94** [comment]
Alright, I merged in #747 which caused a merge conflict. I can resolve that here.

**Comment by jrg94** [comment]
As a bonus, I reordered the programs alphabetically.

**Comment by auroq** [comment]
@jrg94, I updated this to use the same error handling that I used in #747. For that handling I did use `>>=` which is somewhat of an advanced concept in haskell. However, it makes things really clean, and I don't think it will confuse the beginner unless they try to dig deep into it.

If you're alright with it, I'd like to update Fibonacci in Haskell to use the same handling.

To be fair, in my opinion IO in haskell is not really a beginner concept due to the nature of haskell being a [pure functional language](https://stackoverflow.com/questions/4382223/what-does-pure-mean-in-pure-functional-language)

**Comment by jrg94** [comment]
Good to know! I just learned Lisp, so I'm growing familiar with the idea of pure functional languages. I think this looks great, and you're free to update fibonacci. 

On a side note, we should probably add test cases to these problem descriptions if they don't already exist.

**Pull request merged**
