### PR TITLE
Fibonacci in C#

### PR DESCRIPTION
**Pull request by MariusGarbea**
## Please Complete the Following

- [ ] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README

### CODE REVIEW

**Comment by jrg94** [comment]
Alright, so we don't have fibonacci yet in our contribution doc. Would you mind writing something up and adding it [here](https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md). You can use the same pull request :)

**Comment by jrg94** [comment]
Also, I think for consistency we should use the SamplePrograms namespace. Although, my C# friends can correct me!

**Comment by MariusGarbea** [comment]
Yeah, I am aware of that. Should I just return the n-th fibonacci number?

**Comment by jrg94** [comment]
Up to you! I'm comfortable with whatever 👍 I apologize if I came off like a jerk. I just like to nail down our implementation, so we can keep things consistent as we dig into other languages.

**Comment by MariusGarbea** [comment]
Oh ok, so you want all the fibonacci implementations to follow the same exact algorithm? I am about to submit some more pull requests for fibonacci in another languages.

**Comment by jrg94** [comment]
Yes! That’s the idea. If we don’t define clear requirements, someone will come along and complain later. And, it makes for tough cleanup. We saw that a lot with reverse a string. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MariusGarbea** [comment]
Ok, I am pushing a new commit in a sec

**Comment by jrg94** [comment]
Clever! I like this a lot. Now, does it make sense to have it print just the nth term? For instance, a python program would look like:

```
python fibonacci.py 5
34
```

I’m not sure it matters. Just spitballing. Haha

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Alright, I updated the rules a bit. Let me know if you're comfortable with them.

**Comment by MariusGarbea** [comment]
The C# program prints every fibonacci number up to n, not just the nth one. And yes, I'm comfortable with the rules. I will add some more languages once this PR is approved.

**Comment by jrg94** [comment]
This prints it vertically, right? I want to notate that in the rules.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Okay! Before we finish this off, I have one last suggestion (I apologize for being difficult. I’m anticipating future complaints haha).

Can we do one of the following:

1. Print the sequence as you did but with the Yerma numbered appropriately: 

```
1: 1
2: 1
3: 2
4: 3
5: 5
```

2. Alternatively, we just print the nth term following the mapping above.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Perfect! Now the last thing is to update the contributing doc to show the proper output. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Then, we can get this merged 🤣 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MariusGarbea** [comment]
Yeah sure

**Pull request merged**
